### ISSUE TITLE
Allow User to Set Custom Boxart 

### ISSUE THREAD

**Issue by Retro-Devils** [magneticchen/Daijishou#1]
Hello . 
So really enjoying your frontend .  Amazing stuff .

UPDATED
I think you can allow user to use custom boxart by placing your folder thats in data/user in storage/android/data then more than likely we can drop files thier. I know that works with dig and other launchers . 

I am having trouble getting the scrapper to work at all for art info gets fine.

**Comment by Retro-Devils** [comment]
So I see now where scrapper is trying to put files. 
If this was in /android/com.........../boxart and video etc. 

Then user can mainly put those boxart thier .

**Comment by Retro-Devils** [comment]
Examine more and more lol .

They way the scrapes setup will cause issues for importing imo. 
..../Preview-media/1.png will be hard to translate. 

I suggest using same paths as most for example 
...../media/nes/boxart/super Mario 3.png 
...../media/nes/cartart/super Mario 3.png 

If you use the scraped names should work the same . 
.

**Comment by magneticchen** [comment]
Currently working on it and to allow user to set custom preview medias path like SD card.

**Comment by magneticchen** [comment]
User can set custom boxart started from version 60 (1.1.34).

**Comment by Retro-Devils** [comment]
Awesome.  
When you say folders won't follow game name what do you mean ? I don't understand .

In theory when scrapping super Mario bros 3 save to ....../nes/boxart/supermario3.png instead ..../1.png .

A LOT of users will not use with they can t import boxart . It will be very difficult to import if they are saved as 1, 2 , 3 , 4 etc . 
We will have to remeber what order we added games in .

**Comment by magneticchen** [comment]
Because a file with same checksum or hash can has different filenames based on user's preferences or download sources. For example "mario bros" "mario bros." "mario bros(USA)"

**Comment by Retro-Devils** [comment]
Ok . Interesting 
Heres  example in other launchers if my Mario bros is named Mario Bros USA and my boxart is also Mario Bros USA it works . 

So search game name save image as game name . Again in theory

**Comment by Retro-Devils** [comment]
I see what you did with custom boxart.  On my tablet works good.  Android 10

I see its below android 11 I assume this is cause scoped storage .

**Comment by magneticchen** [comment]
That's not only about scope storage but also external storage permissions. Google limited such permission unless you submitted reports which still mostly rejected by google unless you really has good reasons. Google no longer treat file systems as API that can be directly manipulated. Each folder has its specific usage.
