### ISSUE TITLE
關於遊戲啟動後的屏幕問題

### ISSUE THREAD

**Issue by crhhahaha** [magneticchen/Daijishou#101]
您好！我正在使用的是微軟的surface duo雙屏幕手機，我已經設置了相應的模擬器應用程式全屏啟動，但是我用daijisho啟動時，daijisho擋住了我的下半部分屏幕

另一個問題：在遊戲界面中，背景色偶爾會出現灰色背景，原本應該是黑色才對

以上兩個問題請看錄屏，謝謝作者的製作！

**Comment by crhhahaha** [comment]
https://drive.google.com/file/d/1-nFbRpAL3kpiSkePq1DdVrSfvBF10HYb/view?usp=drivesdk

**Comment by magneticchen** [comment]
您好。想請問幾個問題。

1. Dai 是否被設定為主畫面應用程式。
2. 是否只發生在幾個特定的模擬器。
3. 請問黑色畫面是指在於Dai裡面還是在模擬器中。

感謝。另外我沒有雙螢幕手機，所以恐怕會不好Debug。 😢

**Comment by crhhahaha** [comment]
1，沒有設定為默認桌面，因為設定後會桌面bug，dai只能橫屏適用所以雙屏機器不能設置成桌面
2，每個模擬器都有可能觸發灰色背景，這個在我的單屏幕手機上也出現了，應該和模擬器關係不大
3，在模擬器中，錄屏中某一次出現了灰色，並且已經進去了遊戲

感謝答复
