### ISSUE TITLE
Dai的布局功能需求

### ISSUE THREAD

**Issue by crhhahaha** [magneticchen/Daijishou#102]
我之前有提到雙螢幕手機的打開問題，我發現了問題所在：

Dai不能作為雙螢幕手機的案頭，因為系統需要他在兩塊螢幕上顯示app，我通過設定強制dai全屏打開，並且強制豎屏展示後，設定為默認後，結果dai崩潰了，導致手機強制性重啓。

猜測：

1，不能作為默認launcher的bug不是和強制豎屏有關，默認橫屏時候依然崩潰，但其他手機正常設定成功

2，希望加入一個豎螢幕佈局，ui上半部分顯示原本的詳細資訊，ui下半部分顯示原來的網格顯示

個人覺得豎螢幕ui顯示還是挺需要的，希望可以加入，現時從天馬前端轉過來，一切都很喜歡，推薦給了很多朋友！
![aecfdaf4f9eeae23609230ece7641b4](https://user-images.githubusercontent.com/87603208/195418452-002d9922-172a-4d51-844c-0773282bf0d5.jpg)

**Comment by magneticchen** [comment]
您好。前一篇因為我自己無法重現Bug，目前仍然沒辦法想到解決辦法，想了許久也還沒想到如何reproduce相關問題。 囧rz

另外就是崩潰的問題能否在搜尋欄中輸入「howdoyouturndebugon?」如此一來，Dai就會顯示崩潰訊息。方便偵錯。

「howdoyouturndebugoff?」便可關閉。

另外您針對雙螢幕手機建議，聽起來都是很好建議，可惜由於自己沒有這樣的裝置，心有餘而力未逮。

謝謝您的愛用。 ^_^

**Comment by crhhahaha** [comment]
我打開了之後手機會無限重啓，不會像之前一樣重置默認案頭了，會一直出現這個畫面後重啓
![983f1c0e9c1572680e7c21946326f78](https://user-images.githubusercontent.com/87603208/195426735-a366275f-235a-4788-8137-b5468a8a7b93.jpg)

**Comment by crhhahaha** [comment]
天哪我該怎麼辦，連換回默認案頭都不行了，甚至沒有方法可以恢復出廠設定

**Comment by magneticchen** [comment]
> 我打開了之後手機會無限重啓，不會像之前一樣重置默認案頭了，會一直出現這個畫面後重啓
> ![983f1c0e9c1572680e7c21946326f78](https://user-images.githubusercontent.com/87603208/195426735-a366275f-235a-4788-8137-b5468a8a7b93.jpg)
> 

上面的資訊可以幫助除錯，感謝。

防止重啟請把除錯模式關閉。
「howdoyouturndebugoff?」

**Comment by crhhahaha** [comment]
行不通，因为桌面并没有启动

**Comment by magneticchen** [comment]
可能要先換掉預設主畫面。

**Comment by magneticchen** [comment]
可能要先換掉預設主畫面。
滑下通知欄，通常可以進入設定頁面。

**Comment by magneticchen** [comment]
> 我通過設定強制dai全屏打開

經過調查這應該是原因。

**Comment by magneticchen** [comment]
請嘗試看看此[更新](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.33)。

**Comment by crhhahaha** [comment]
> 请尝试看看这个[更新](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.33)。

剛剛嘗試了一下，和昨天沒有變化，感謝update，但我決定放棄了

**Comment by magneticchen** [comment]
好的。抱歉了。😐
