### ISSUE TITLE
Box art scrapping not working 

### ISSUE THREAD

**Issue by bkcin** [magneticchen/Daijishou#104]
No box art is scrapped after syncing. 

If manually synced, the scrapping process does start, but stops with no successful result. 

[Screen recording](https://photos.app.goo.gl/k42PQBB12MV6KgGA7)

Android 13 on Google Pixel 7.

**Comment by savethekiddes** [comment]
The best hypotesis I have is that servers are offline. Please try to sync with an unzipped copy of New Super Mario Bros in your library.

**Comment by bkcin** [comment]
@savethekiddes 
It's quite unclear what the problem is because I can't even go into the "edit item" menu. The app crashes.
Too many variables tho. It's entirely possible that it's the brand new Pixel 7 somehow being buggy. I don't have another device to test it with.

**Comment by RedHatDev-8bit** [comment]
I don't think it's Pixel 7. I have a realme device have same issue. Daijishou used to scrape all my arcade romset properly but it's now just stop in a sec without scraping art work at all.

**Comment by magneticchen** [comment]
Thanks for reporting. Have fixed in the latest version.
