### ISSUE TITLE
Feature Request: Add platform option for Android games.

### ISSUE THREAD

**Issue by RebelKhaotic** [magneticchen/Daijishou#105]
Using daijisho as my launcher on my ayn Odin is nearly perfect! However, the need to go into the clutters apps tab to access all Android games is somewhat combersome. I used to use launchbox, and this provided a platform section for the Android games I had installed. Having an option like this in daijisho would incredible.

**Comment by Jetup13** [comment]
Try this [Android json](https://github.com/magneticchen/Daijishou/blob/main/platforms/Android.json.deprecated) file > Open Daijishou > `Settings` > `More Settings` > `Import Platform` > Select the .json file

Go to the Android platform > Click Sync

**Comment by magneticchen** [comment]
Follow what Jetup said should work. 👍
Also please check out [this](https://github.com/magneticchen/Daijishou/issues/37).
