### ISSUE TITLE
AetherSX2 does not exit fully when pressing back button.

### ISSUE THREAD

**Issue by lazyradly** [magneticchen/Daijishou#109]
When pressing the home button to go back to the Daijisho launcher, the game does not exit fully. Selecting a different game only reboots the previous one. So far, I've only seen it happen with the PlayStation 2 games (AetherSX2).

There is a workaround by going into the AetherSX2 menu and selecting "Exit Game".

https://user-images.githubusercontent.com/14238446/196122430-23d93412-ec4b-4c83-ba13-c5efbed7d0ad.mp4

**Comment by savethekiddes** [comment]
I don't think this is a problem of Daijishou itself, as I'm sure you will encounter similar problems with other frontends too. Still, you could workaround your way out via [Button Mapper](https://play.google.com/store/apps/details?id=flar2.homebutton)

**Comment by lazyradly** [comment]
Not true, RESET Collection does not have this issue with AetherSX2.

For now, the easier workaround is to press back and click Exit Game and it will bring me back to the Daijisho menu. Not too annoying, but it is inconsistent with the other systems.

**Comment by savethekiddes** [comment]
@magneticchen
