### ISSUE TITLE
Can't sync

### ISSUE THREAD

**Issue by IAmAGitHubb** [magneticchen/Daijishou#11]
I CANNOT SYNC GAMES

**Comment by magneticchen** [comment]
Please describe your problem more specifically. Did you added your sync paths?

**Comment by IAmAGitHubb** [comment]
What sync paths? Show me a tutorial on how to sync

**Comment by SoumyBhow** [comment]
On the main page, near the bottom right on each platform, there is a plus button. That's where you add the path of the ROMs for the platform

**Comment by IAmAGitHubb** [comment]
OMG 😱 IT WORKS! THANKS TO YOU!
