### ISSUE TITLE
Opening N64 ROMs to Mupen64 does not work

### ISSUE THREAD

**Issue by geninchuni** [magneticchen/Daijishou#110]
When I try to open any N64 ROM I get a "couldn't find ROM" error in Mupen64.
My ROMs are in the SD card, I already tried to re-add the path multiple times

https://user-images.githubusercontent.com/70247300/196203664-c925375c-bd0c-4f67-a5fc-18aa570708cf.mp4

**Comment by savethekiddes** [comment]
So try changing file.uri with file.path in the platform settings or viceversa. Also assure that mupen64fz has storage permission

**Comment by savethekiddes** [comment]
It is possible that the [SAF fix](https://github.com/magneticchen/Daijishou/issues/68) might have caused some problems with newer version of mupen64fz
