### ISSUE TITLE
Game Gear Json Should Be Fixed

### ISSUE THREAD

**Issue by DNAMobileApplications** [magneticchen/Daijishou#111]
Game Gear using com.androidemu.gg known as Gearoid needs to be changed to d {file.path}\n  instead of uri can you edit this so the correct Json script is download please.

**Comment by savethekiddes** [comment]
If you want a momentary fix, know that you can edit from daijishou or edit it on a text editor and load it as a json

**Comment by DNAMobileApplications** [comment]
> If you want a momentary fix, know that you can edit from daijishou or edit it on a text editor and load it as a json.
> 
> Btw, geardroid is MORE than legacy, as it was designed for android 4.4/5. I suggest you to use retroarch.

Hey so I already found the fix, I did a video series all about Daijisho with the fix included!  Also Gearoid is awesome, works perfectly on the Pocket 2+ haven't had any issues plus it's the easiest method as of right now to get Game Gear games working right away.   Anyways thanks for the reply, I'm an Android dev so I tried deep diving then thought to change the path from uri and it worked 😄.  This app is amazing again definitely a must have, now it needs a device that comes preloaded with Daijisho as the main OS 😉

**Comment by magneticchen** [comment]
Thanks I have updated it.

**Comment by DNAMobileApplications** [comment]
> Thanks I have updated it.

Perfect! 🥰
