### ISSUE TITLE
Ability to swap buttons/configure controller mapping

### ISSUE THREAD

**Issue by spicybackend** [magneticchen/Daijishou#112]
On the Ayn Odin with the gamepad configured in "xbox" mode, the A and B buttons are swapped as B and A, respectively.

It would be good to be able to swap the accept/cancel buttons, or otherwise provide more configuration around controller buttons beside the other hotkey settings in the app.

**Comment by savethekiddes** [comment]
Test

**Comment by magneticchen** [comment]
There is an option that allows you to swap a/b buttons aesthetically.
