### ISSUE TITLE
Ability to sync config to multiple android devices.

### ISSUE THREAD

**Issue by minifluff** [magneticchen/Daijishou#118]
I'm hoping this can be added to t
Frontend. Currently I use launchbox and use Onesync to sync my launchbox config to every one of my handhelds. Currently with daijishou I can't find a config folder to do the same with it. Having it built in or config accessable would be great.

**Comment by magneticchen** [comment]
Thanks for the feedback. Planing to add backup and restore options coupled with Google drive upload in 1.4 update. Should provides similar features you might want.

**Comment by minifluff** [comment]
This will make it easier to copy the config from one to another handheld. My current solution is automatic. So if I add a new game on one or fix an issue I don't need to do anything with the rest of my handhelds.

**Comment by goyetus** [comment]
> I'm hoping this can be added to t Frontend. Currently I use launchbox and use Onesync to sync my launchbox config to every one of my handhelds. Currently with daijishou I can't find a config folder to do the same with it. Having it built in or config accessable would be great.

Would Love to see exactly the same.  I asked them to make the "emulator config files"  in a writeable folder to Sync  it between different devices.....   But I think it will not be implemented.  :(

**Comment by magneticchen** [comment]
Google drive backup and store have been added in 1.4.x. (Syncing is not practically possible, need a backend to do that.)
