### ISSUE TITLE
Can't Launch into a Dreamcast Game Directly Using Redream

### ISSUE THREAD

**Issue by saskwatch** [magneticchen/Daijishou#119]
it is my understanding that latest version of Redream supports front-ends, yet I cannot launch a game directly into the emulator.  I am using the latest version of Daijishou (1.3.34) and Redream (1.1.98).  I watched Youtuber ETA Prime getting this to work ([YT Video](https://www.youtube.com/watch?v=DmCT10bb9xw)) but I am not able to.  I am trying to do this with a Samsung Galaxy Note 20 and a Galaxy Tab 7+ with no success. Please advise.

**Comment by magneticchen** [comment]
Please make sure you've updated to the newest version.

**Comment by Post-Mortem** [comment]
> it is my understanding that latest version of Redream supports front-ends, yet I cannot launch a game directly into the emulator. I am using the latest version of Daijishou (1.3.34) and Redream (1.1.98). I watched Youtuber ETA Prime getting this to work ([YT Video](https://www.youtube.com/watch?v=DmCT10bb9xw)) but I am not able to. I am trying to do this with a Samsung Galaxy Note 20 and a Galaxy Tab 7+ with no success. Please advise.

Works fine for me.

**Comment by saskwatch** [comment]
I figured out the problem. Redream on Android must have permissions to manage all files for this to work. Go to settings on your Android device... Apps... Redream... Permissions to make sure that permission is turned on.

**Comment by magneticchen** [comment]
Thanks for reporting your experience!
