### ISSUE TITLE
Missing cores/not able to find certain cores

### ISSUE THREAD

**Issue by codiac2600** [magneticchen/Daijishou#120]
Good day and thank you for the awesome launcher. 

I only have one issue and that’s a few systems I cannot launch in my preferred core because they do not exist in this launcher. I would try to use the suggested core in your launcher but they do not exist in retroarch anymore. 

1. Colecovision I’m currently using gearcoleco and it’s not available to select. 
2. Commodore64 I’m using VICEx64 which also doesn’t exist in the launcher as an option. 
3. For turbographx I use BeetlePCE and the one suggested on your launcher doesn’t exist as an option either. 

I’m using the nightly build of retroarch 1.12.0 on the Retroid Pocket 3. 

Thank you.

**Comment by Jetup13** [comment]
Gearcoleco shows up here in the platform: [64bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/ColecoVision.json#L34), [32bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/ColecoVision.json#L52), [mixed bit retroarch](https://github.com/magneticchen/Daijishou/blob/main/platforms/ColecoVision.json#L70)

Vicex64 shows up here: [64bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/Commodore64.json#L54), [32bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/Commodore64.json#L92), [mixed bit retroarch](https://github.com/magneticchen/Daijishou/blob/main/platforms/Commodore64.json#L131)

BeetlePCE shows up here: [64bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/TurboGrafx16.json#L44), [32bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/TurboGrafx16.json#L64), [mixed bit retroarch](https://github.com/magneticchen/Daijishou/blob/main/platforms/TurboGrafx16.json#L83)

Try updating the platform: Download > Select the Platform(s) > Import

**Comment by codiac2600** [comment]
> Gearcoleco shows up here in the platform: [64bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/ColecoVision.json#L34), [32bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/ColecoVision.json#L52), [mixed bit retroarch](https://github.com/magneticchen/Daijishou/blob/main/platforms/ColecoVision.json#L70)
> 
> Vicex64 shows up here: [64bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/Commodore64.json#L54), [32bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/Commodore64.json#L92), [mixed bit retroarch](https://github.com/magneticchen/Daijishou/blob/main/platforms/Commodore64.json#L131)
> 
> BeetlePCE shows up here: [64bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/TurboGrafx16.json#L44), [32bit](https://github.com/magneticchen/Daijishou/blob/main/platforms/TurboGrafx16.json#L64), [mixed bit retroarch](https://github.com/magneticchen/Daijishou/blob/main/platforms/TurboGrafx16.json#L83)
> 
> Try updating the platform: Download > Select the Platform(s) > Import

I’m currently looking at the list and none of those are showing up. Let’s run an update. 

Okay. I’ve gotten colecovision and commodore64 to show up. Sadly I need to find a different bios for colecovision it seems. 

Turbographx nothing. Not showing up. I can only select Mednafen_pce_fast which is not available in the nightly build of retroarch cores.

**Comment by BeF1990** [comment]
Hi. I've just discovered this amazing frontand and I love it!

But I have one issue, I can't set PUAE 2021 (the best Commodore Amiga core from RetroArch) because the frontend doesn't have this one on the list.

Any chance to add it?

**Comment by koh0000** [comment]
@codiac2600

I had same problem and found out mednafen_pce_fast is Beetle PCE Fast

https://docs.libretro.com/library/beetle_pce_fast/
> Beetle/Mednafen PCE FAST is a libretro port of Mednafen PCE Fast with the PC Engine SuperGrafx module removed.

**Comment by thespianuk** [comment]
> Hi. I've just discovered this amazing frontend and I love it!
> 
> But I have one issue, I can't set PUAE 2021 (the best Commodore Amiga core from RetroArch) because the frontend doesn't have this one on the list.
> 
> Any chance to add it?

Brilliant front end - same issue for me with Amiga PUAE 2021 not showing in available cores.  Would be brilliant for it to appear as it works beautifully on hardware like the Retroid Pocket 3+.

**Comment by magneticchen** [comment]
PUAE 2021 is now included.
