### ISSUE TITLE
3DS Games giving an error after trying to launch into Citra MMJ

### ISSUE THREAD

**Issue by MindlessZapper** [magneticchen/Daijishou#121]
I loaded some 3DS games onto my SD Card, adding the 3DS platform on the Daijisho launcher and selecting that location, however, after launching a game, Citra MMJ starts and immediately closes, briefly showing an error "ROM format not supported" or something similar. Everything else works fine, but even normal Citra emulator on Daijisho does not work and also leaves an error.

**Comment by MindlessZapper** [comment]
Also, not to mention I AM on the latest version (1.3.34)

**Comment by magneticchen** [comment]
I’ve gave up supporting citra . 👍 
There are some previous discussions about it on Discord #Help me channel.
You can take a look to see if there are any clues.
Those citra devs really messed up with forks and versions.

**Comment by MindlessZapper** [comment]
Ah, I see. thanks for the info.

**Comment by savethekiddes** [comment]
3ds is discontinued. Jetup made a custom 3ds platform if I remember correctly.
