### ISSUE TITLE
Wallpapers won’t change

### ISSUE THREAD

**Issue by 2Lujan** [magneticchen/Daijishou#122]
Tried to see how other wallpapers would look, when I download some of them all of the platforms have the arcade wallpaper, others don’t even apply. Here’s a video of the issue: https://drive.google.com/file/d/1-ACN2Y0Lwtme_-To79pPjTTp8H45CPZW/view?usp=drivesdk

**Comment by magneticchen** [comment]
Hello. It is because your platforms shortnames didn't follow the standard config on the GitHub page.

**Comment by 2Lujan** [comment]
Thank you for the quieck response, I thought that could be the problem. How can I fix it?

**Comment by magneticchen** [comment]
You have to have the shortname be corrected. Otherwise the pack cannot detect your platforms/systems.
