### ISSUE TITLE
310 - Paths & Edit Options Missing After Initial Setup

### ISSUE THREAD

**Issue by hayashiLS** [magneticchen/Daijishou#125]
Currently running Daijisho on an Android 8.1 device:

- With build 310 (1.3.34) after initially setting up the relevant platforms, the Paths and Edit button go missing whether on the game library menu or when I'm trying browsing a specific game and viewing its boxart/metadata. So I can't edit game titles or delete/unlink games.
- With build 309 (1.3.33), the buttons remain there, but box art/metadata do not show up no matter how much I fiddle with the sync/scraping.

**Comment by hayashiLS** [comment]
Disregard. I pulled the apk from github as opposed to from the Play Store and the issue is resolved.

**Comment by magneticchen** [comment]
Please check that kiosk mode is not enabled

**Comment by hayashiLS** [comment]
Ah, I feel super silly. Thank you!
