### ISSUE TITLE
Default start up tab

### ISSUE THREAD

**Issue by yauwaijoe** [magneticchen/Daijishou#130]
It is a great front-end, and I am using it on my RG552, Rertroid Pocket 3 and Odin Lite. Thanks!

Just one suggestion, if I was in the "Highlight" tab and quit the app, it will default to the "Setting" tab when I open the app again. It will be great if it can start at the last tab I opened, or adding an option to select the start up tab.

Many thanks!

**Comment by magneticchen** [comment]
It's weird because Dai is supposed to start from where you left off already. It should not start from the settings tab. If you have already stayed at another tab.

**Comment by yauwaijoe** [comment]
My scenario is I have hide the "Widgets" and "Apps" tabs, so I just have "Platforms", "Highlight" and "Settings" tabs enabled.
There is no issue if I have eanble both "Widgets" and "Apps" tab.

**Comment by magneticchen** [comment]
Yes. Didn't notice the issue before. Thanks for reporting.

**Comment by magneticchen** [comment]
Will be fixed next version. 1.3.38(315)
