### ISSUE TITLE
[Feature request] J2ME

### ISSUE THREAD

**Issue by telanus** [magneticchen/Daijishou#137]
1) If you import games from a preexisting j2me-loader instance, all the games are imported as res, and you have to rename every last one. Is it possible to have Daijishou import them with their names (could use the name in the directory)?

2) possible to have j2me-loader autostart the game instead of the current behaviour?

**Comment by magneticchen** [comment]
1. Nope. It will increases the complexities.
2. No. I've tried it several times. No luck.
