### ISSUE TITLE
Add standalone apps for Pico-8 and GBCC + misc

### ISSUE THREAD

**Issue by WingofaGriffin** [magneticchen/Daijishou#139]
Pico-8 has a standalone app: https://play.google.com/store/apps/details?id=com.ylstudios.p8player&hl=en_US&gl=US `com.ylstudios.p8player`

GB/GBC has an additional standalone app that is open source https://play.google.com/store/apps/details?id=com.philj56.gbcc `com.philj56.gbcc`

Some other Misc ones:
- TIC-80 has an android APK on git, though it doesn't have onscreen controls to the best of my knowledge: https://github.com/nesbox/TIC-80/releases/latest
- https://emulation.gametechwiki.com/index.php/Emulators_on_Android has a pretty updated and complete list, though obviously I think it is a fool's errand to try to support every single one of these. I would suggest looking at the Active+Recommended apps for supported (and future supported) platforms in the frontend, and add in their app IDs now if possible.

**Comment by WingofaGriffin** [comment]
Additionally adding MD.emu as supported for Sega CD.

**Comment by magneticchen** [comment]
Hello. Take a while to test. And here are the results.

1. com.ylstudios.p8player: The app does not support launching externally.
2. com.philj56.gbcc : The app does not support launching externally.
3. com.ylstudios.p8player(TIC 80): The app launches but didn't open the game.
4. MD.emu: Yes. Have updated.

**Comment by WingofaGriffin** [comment]
Created a FR for GBCC here: https://github.com/philj56/gbcc-android/issues/61
