### ISSUE TITLE
[Feature Request] Alternative to using Storage Access Framework for path selection

### ISSUE THREAD

**Issue by DiskTurbo** [magneticchen/Daijishou#140]
Dai is probably the greatest Android frontend I've used, but on a couple of the devices I tried to use it on I simply cannot add ROM paths due to the storage access framework not existing on the device. I unfortunately could not find any way around this. I hope it is possible to look into implementing an alternate file choosing library to have in addition to using storage access framework, like Dig allows.

**Comment by magneticchen** [comment]
Sorry. But Dai is natively SAF. And I am not currently planing adding it, since adding absolute paths can break the integration. That's why Dai adapts newer android version a bit better then Dig. But this means that Dai will unable to run on most Android TVs.
