### ISSUE TITLE
Any way to Backup "config files"  ?   Maybe by using an external path ?

### ISSUE THREAD

**Issue by goyetus** [magneticchen/Daijishou#141]
Any way to backup the config files once all the emulators  are  configured into daijishou ? 
Maybe using an external route inside the Android writable partition?

We are into research to develop full custom for several android consoles.......  but can not port config  from one to another.

Could you add an external path to load the config files?    

Regards!!!!

**Comment by magneticchen** [comment]
Yes. You can export configured platform by clicking "Share" button in platforms page.

**Comment by magneticchen** [comment]
#118

**Comment by sammcj** [comment]
That seems to per platform, is there no way to export all your config / database?
