### ISSUE TITLE
Anyway to make BoxArt open for user edition through files and config rather than using APP UI?

### ISSUE THREAD

**Issue by guschen802** [magneticchen/Daijishou#142]
scraping through Daijishou is not always working. There are tons of options on PC to do efficient scrapping like Screen Scraper and people may have their Box art scrapped for tens of thousands of games already. 

i think it maybe more efficient to let use provided already scrapped files like what Onion OS did for Miyoo mini or gamelist.xml for emulationstation

**Comment by magneticchen** [comment]
No. Because of the SAF from google/Android. Also, self-managed images let Dai's caching mechanism being responsive. Since every changes are captured by Dai.
