### ISSUE TITLE
Can't sync Atari Lynx games

### ISSUE THREAD

**Issue by sfreyux** [magneticchen/Daijishou#144]
Version 1.3.35 (311).
I try syncing my Atari Lynx games (I added the path in Daijishou, all my games are inside their own .7z file just like many other systems which I synced with no issue, also I checked the default regex for Atari Lynx on regex101.com) but when I tap the sync button nothing happens.

It doesn't even scan the folder to analyze the files, it's like I added an empty or non-existent path, but the folder and files are there.

**Comment by magneticchen** [comment]
Hello. May I ask which emulator/core you are using that supports .7z files. Thanks.

**Comment by sfreyux** [comment]
> Hello. May I ask which emulator/core you are using that supports .7z files. Thanks.

Both Beetle Lynx and Handy support games inside .7z files, even though the respective core info files state that they're compatible with .lnx and .o files.

In fact, I've been able to scan my Lynx games into a RetroArch playlist using the automatic scanner, and I can play them from within RetroArch with no issue. It's just that I'd like to sync them into a Daijishou system collection.

**Comment by magneticchen** [comment]
Thanks for reporting. Have updated. You can download and replace the currently platform you have. Or restart Dai with internet connection.

**Comment by EgoBizarro** [comment]
I think the unpacking is done by RetroArch itself and it supports ziüp and 7z so all cores should support it AFAIK.
