### ISSUE TITLE
Another option for official ps2 emulator

### ISSUE THREAD

**Issue by hans2124** [magneticchen/Daijishou#146]
Please, include the official alternate version of the AetherSx2 emulator called: custom-turnip. It is the best option for computers with Adreno gpu. Let it be another option to choose from.

You have to modify:

xyz.aethersx2.android

For this directory:

xyz.aethersx2.custom

Ejem:

            "name": "ps2 - Aethersx2",
            "description": "Supported extensions: iso, chd, gz.",
            "acceptedFilenameRegex": "^(.*).(?:iso|chd|gz)$",
            "amStartArguments": " -n xyz.aethersx2.custom/.EmulationActivity\n -a android.intent.action.MAIN\n -e bootPath {file.uri}\n --activity-clear-task \n --activity-clear-top \n ",
            "killPackageProcesses": true,
            "killPackageProcessesWarning": true,
            "extra": ""

**Comment by magneticchen** [comment]
Thanks. Added!
