### ISSUE TITLE
Save and/or state files, cloud sharing between devices

### ISSUE THREAD

**Issue by SoFLazerTag** [magneticchen/Daijishou#147]
Would be nice to save on one device and it be available on another device.  Any chance this is something Daijishou could handle? maybe similar you have planned with the backup/restore to Google drive?

**Comment by magneticchen** [comment]
#118

**Comment by kid1412621** [comment]
> #118 

Just to be sure, currently Daijisho only backs up its configs to google drive, not including the states and saves files across standalone players, right?
