### ISSUE TITLE
Game Cover Scraping [Boxart] issue
[Android] / Not showing correct Boxart based on Region

### ISSUE THREAD

**Issue by RFL0WGitPR** [magneticchen/Daijishou#148]
***//Issue***

Daijishou does correctly add [index] my games into a playlist 📀💿💾🗂️🗃️

Format File Extensions used

iso, .rvz, .wbfs, .gdi, .chd, .pbp, ciso, Decrypted.3ds, .cia nes, .z64, .ds, .sfc, .zip, .exe. 

👇👇👇
However is fails to scrape my rom backups with the correct [Boxart] from my Region [NTSC / USA]

Instead the Cover Art [Boxart] it gives me is PAL Region Boxart 

All the [Games] in my collection are [NTSC] all of my iso images and ROM backups dumps are as well NTSC-U based

**// Suggestions to fix issues*** 

Daijishou should understand if it says (USA) (En) in the file name wile indexing so when a user decides to scrape it shows the correct regions Boxart 

Consider getting Boxart Artwork from correct regions maybe from new Boxart Image sources (API) from sources like: 

***-  The Games Db.***
***-  MobyGames.***
***- PSX Database.***

***// My Device***

Daijishou ver: 1.3.37 APK [Git]
Platform: Android 11
Display resolution: 6.7" FHD+ Max Vision Display, FHD+ (2400x1080).
Device: Motorola One Ace 5g (T-Mobile)
RAM : 6GB RAM.
CPU: Qualcomm Snapdragon 750G 4G RAM

**Comment by magneticchen** [comment]
I've used a bad regex for libretro scraper in 1.3 versions. In 1.4 the issue should be mitigated.
