### ISSUE TITLE
Video Previews/Media

### ISSUE THREAD

**Issue by Retro-Devils** [magneticchen/Daijishou#15]
Possible to get or import video previews ? 

Be really cool to have video as a option in Daijishou.

**Comment by magneticchen** [comment]
Have added youtube preview video fetched by IGDB API in the newest version.

**Comment by Retro-Devils** [comment]
Cool . I just tested worked fine .

**Comment by Retro-Devils** [comment]
This is really cool I personally love it . 

I don't know how users will like .  Most frontends like DIG and stuff allow switch to video like you have preview and screenshot .

**Comment by Retro-Devils** [comment]
So I had a suggestion to set video like boxart and preview.  But the way you set up is better click detail then video plays i absolutely love it.
