### ISSUE TITLE
Feature request: hide ROM entries

### ISSUE THREAD

**Issue by npaladin2000** [magneticchen/Daijishou#152]
Right now I'm unlinking and then deleting entries that I don't want shown, but they keep re-detecting on the next sync. This is kind of a pain with files that are normally supported but cause multiple entries, such as manifest.bml files (SNES), bin/cue pairs (or multiple BIN tracks at times), and in particular, M3U files for multi-disc games (where you don't want to filter out the cue or iso files for the single disc games).

**Comment by magneticchen** [comment]
Implemented in 1.4.x
