### ISSUE TITLE
Fix Emulator : Citra Emualtor with Package org.citra.emu_emu not working in 3ds

### ISSUE THREAD

**Issue by Satria7** [magneticchen/Daijishou#154]
Citra Emualtor with Package org.citra.emu_emu not working in 3ds

**Comment by magneticchen** [comment]
I cannot found package name with `org.citra.emu_emu` on the internet. And sources?

**Comment by TheTone82** [comment]
Download the app call My Apk

**Comment by JulienJeon77** [comment]
Actually, it is org.citra.citra_emu, and I am having the same problem

**Comment by magneticchen** [comment]
3DS citra variants are no longer maintained by Daijishou Official.  #121
