### ISSUE TITLE
Can't save state: Error writing file

### ISSUE THREAD

**Issue by rogeriofonseca** [magneticchen/Daijishou#156]
## When I try to save state i receive this message:
<img src="https://user-images.githubusercontent.com/1026153/209249942-eb18a982-d340-4903-9bd6-605bf20ea24d.jpeg" width="600" height="400">

## Even though I allowed writing to the application:
<img src="https://user-images.githubusercontent.com/1026153/209250611-eb7b4be9-3a57-4eec-babc-780f28318b26.jpeg"  width="600" height="400">

### :video_game: Device Type
I am using an **Anbernic RG505** handheld.
### Kind of Emulator
SNES - Super Nintendo Entertainment System

**Comment by magneticchen** [comment]
I think this is related to emulator itself?

**Comment by rogeriofonseca** [comment]
> I think this is related to emulator itself?

Really you are right. The problem was in snes9x.

To resolve. Open the snes9x app
Option >> System >> Save Path: snes >> Select Folder to save

I appreciated your help.
