### ISSUE TITLE
[Android 13] Player error: Unable to find explicit activity class

### ISSUE THREAD

**Issue by cndjonno** [magneticchen/Daijishou#157]
I am getting this toast message when trying to launch an SNES game through Daijishou. Snex9xPlus is installed and and working if I launch it directly.

`Player error: Unable to find explicit activity class {com.explusalpha.Snes9xPlus/com.imagine.BaseActivity}; have you declared this activity in your AndroidManifest.xml, or does your intent not match its declared ?`

v1.3.39
Pixel 5
Android 13

**Comment by magneticchen** [comment]
I've tried it myself. But mine launched.

**Comment by cndjonno** [comment]
Is there anything I can provide to help resolve this issue?  Logs or tests?

**Comment by kerwin-uy** [comment]
I don't know if it helps but I encountered this when I got a new phone running Android 13 (Poco F4 GT) and I didn't have any issues with my old phone running Android 12.

**Comment by maiodin** [comment]
I believe this might help resolve the issue?
Not too sure 
https://stackoverflow.com/questions/73495596/unable-to-launch-arbitrary-activity-since-android-13

It basically is an android 13 issue

**Comment by magneticchen** [comment]
https://github.com/Rakashazi/emu-ex-plus-alpha/issues/1086

**Comment by magneticchen** [comment]
Anyone here can help me confirm that other frontends do not have the issue. Thanks. 🙏

**Comment by magneticchen** [comment]
I've found the solution all we need is to add missing mime type spces `application/zip`.

**Comment by Jurykov** [comment]
Getting a similar error on Android 13 and mupen64plusae.fzurita.  Both pro and non-pro.

> Anyone here can help me confirm that other frontends do not have the issue. Thanks. 🙏

**Comment by Rakashazi** [comment]
I had an issue with my intent filer for non-zip files in Snes9x EX+ and my other emulators, please retest once version 1.5.71 is released in the near future.
