### ISSUE TITLE
Toast messages are cut off

### ISSUE THREAD

**Issue by cndjonno** [magneticchen/Daijishou#158]
My toast messages are only a few words instead of the entire message. 

v1.3.39
Pixel 5
Android 13

![Screenshot_20221225-021437](https://user-images.githubusercontent.com/43080376/209462640-e7780af3-528a-4771-a5e1-d140ac99b20a.png)

**Comment by magneticchen** [comment]
Duplicated. Also the length is determined by Android OS.
