### ISSUE TITLE
Important issues  to make daijishou our "primary"  frontend.

### ISSUE THREAD

**Issue by goyetus** [magneticchen/Daijishou#159]
First all :  Happy Xmas !!!!!

Thanks a lot for your hard work in Daijishou ,  love the frontend. 
We want to use  Daijishou,  even if it goes "paid version".  

Im using "laucnhbox"  cause this two features:

- Cant access media folder  in Daijishou
- Cant access config files in Daijishou

**The problem is when you have diferent portable handhelds  like:   
Phone + Odyn +  Retroid Pocket 3 + Other systems.**

**THE THREE MAIN PROBLEMS FOUND** 

- No sync between systems:
- - Problem:  I try to sync all data between them,  so ,  I cant do it without access to the config files.
- 
- Cant trim down image size and video size.  (really important,   from 8 gb media to 2gb media in my system)
- - Problem: I use TinyPNG and Handbrake to cut size files  (video and photos)  to about 1/3  size.   Cant do this withouth access 
- 
- Cant use Daijishou in our "packs" ,  so I cant spread the glory of Daijishou to other users. 
- - Problem: I cant do any "pack"  to  be downloaded in our Telegram Channel  with all the "media"  

Please,  I will love to use Daijishou as my frontend,   and include it in all the Retroid Pocket,  Phone, and other Device PACKS we do in our Telegram channel,  but  for now,  it seems impossible. 

Hope Daijishou can understand this situation,  and love to see this in the next upgrade.

**Comment by JuanMiguelBG** [comment]
+1

**Comment by magneticchen** [comment]
Sorry for the late response of the suggestion. Here are some changes made to support the features you are mentioning. And the reason Dai doesn't allow external modifications.

1. No sync between systems 
> In 1.4 Daijishou now has a backup restore option.

2. Cant trim down image size and video size. (really important, from 8 gb media to 2gb media in my system)
> Daijishou automatically optimise images imported for the device.

Also another mention.  Daijishō need to dynamically track changes realtime. Thus the system of Daijishō is closed changes keep in the garden. Thus foriegn changes can cause Daijishō breaks down. (If the scripts only run on first launch as a preset for Daijishō then is possible).
