### ISSUE TITLE
Doesn't scan psx roms

### ISSUE THREAD

**Issue by Guillermo4060** [magneticchen/Daijishou#167]
I have detected an error and it is that when I want to add the psx games it does not let me since it does not detect any and I have already checked if they end in (.bin) and they all have them but it does not detect it in the app :(

**Comment by Jetup13** [comment]
You need cue files to accompany the bins. It's bad practice to use just bin files. Especially with CD based consoles (such as PSX, Sega CD, ect). 

If the game is non-CDDA you can use this [tool](https://www.duckstation.org/cue-maker/) to create cue files
