### ISSUE TITLE
NES RetroAchievements

### ISSUE THREAD

**Issue by patrickschuck** [magneticchen/Daijishou#171]
Hello,

I'm trying to play Super Mario Bros. 3 but the information in details when i open the platform and games is another rom, but when i play i win the achievments of correct archive. How can i change this?

![Mario 3 2](https://user-images.githubusercontent.com/94208758/210469765-c962b7ba-087c-4ffb-860d-6b29a4fe60cd.jpg)
![Mario 3](https://user-images.githubusercontent.com/94208758/210469767-9f3eec17-140a-4d2e-9a1b-a3d76403df46.jpg)

Thanks

**Comment by magneticchen** [comment]
Does the problem still exist in 1.3.41?

**Comment by patrickschuck** [comment]
This has been corrected. Thanks
