### ISSUE TITLE
Allow to group duplicated roms

### ISSUE THREAD

**Issue by yannickglt** [magneticchen/Daijishou#176]
ROMs matching the same game (after sync and scrapping) could be grouped under the game name to avoid duplicates in the list.

We should be able to select the main ROM corresponding to the jacket. This ROM would be used on launching the game.

**Comment by magneticchen** [comment]
Hello, thanks for the feedback! This is planned in 1.4.

**Comment by magneticchen** [comment]
Sure, I will close this issue, also mention the related issue. 👍
#50
