### ISSUE TITLE
Allow to hide ROMs without covers

### ISSUE THREAD

**Issue by yannickglt** [magneticchen/Daijishou#177]
Hi,

Thanks for your awesome front-end which makes retro gaming a unique experience. Really thanks for that.

It's nice to suggest more aggressive search for jacket search. 
However, it could be a nice to also be able to hide unmatched ROMs (without any cover) from the list.
It would avoid the pain to manually remove hundreds of ROMs.

**Comment by magneticchen** [comment]
In 1.4 you can now hide ROMs.

**Comment by yannickglt** [comment]
Awesome! Thanks a lot 👍
