### ISSUE TITLE
PS Button Symbols

### ISSUE THREAD

**Issue by IAmTheRedSpy** [magneticchen/Daijishou#180]
As someone that's more used to the symbols (cross, circle, square, and triangle) on PlayStation controllers, I wish I could set everything to use them instead. For daijishou, this would mean making cross (X) and circle (O) options for the confirm and cancel hints in the bottom right.

**Comment by magneticchen** [comment]
I would like to but those are [trademarked](https://gamedev.stackexchange.com/questions/61181/can-i-use-playstation-controller-button-icons-in-my-game)

**Comment by IAmTheRedSpy** [comment]
Interesting. Based on their presence on [Wikimedia](https://commons.m.wikimedia.org/wiki/File:PlayStationTriangle.svg), they don't seem to enforce the copyright. I also don't see them on [the list of PlayStation copyrights](https://www.playstation.com/en-us/legal/copyright-and-trademark-notice/).

I wonder if Wikipedia, the source of that stack exchange answer, is outdated or misleading.

**Comment by kacboy** [comment]
Perhaps directional button symbols like on the Switch when you have a single sideways joycon would be more neutral and copyright free?

rough example
![image](https://user-images.githubusercontent.com/19754966/232981474-8508a549-bf1a-4f74-9975-213a01c0d0a2.png)

**Comment by IAmTheRedSpy** [comment]
Retroarch uses that system. I guess it could provide a more uniform experience? I'm a fan.
