### ISSUE TITLE
Problem with Melonds android

### ISSUE THREAD

**Issue by stepsy** [magneticchen/Daijishou#183]
I've tried to launch the games from the app but all I got is this.
![Screenshot_20230114_170940](https://user-images.githubusercontent.com/114864941/212465642-a8c181fb-50af-4314-90c5-67e4d4d30e35.jpg)
I tried both play store and GitHub version of melonds.

**Comment by Jetup13** [comment]
Usually this is an Android permissions issue. Have you tried adding the same NDS folder to MelonDS itself?

**Comment by stepsy** [comment]
> Usually this is an Android permissions issue. Have you tried adding the same NDS folder to MelonDS itself?

![Screenshot_20230114_190728](https://user-images.githubusercontent.com/114864941/212469022-58f59183-c525-47e5-b7ba-63af66f2eef3.jpg)

**Comment by Jetup13** [comment]
And the games launch from MelonDS itself? Not sure beyond that. 

Only way I can reproduce the same error is if the folder wasn't found within MelonDS. I should note that I used the latest build [here](https://github.com/rafaelvcaetano/melonDS-android/actions) as the others are a few years old. There's also the MelonDS core available on Retroarch.

**Comment by stepsy** [comment]
I don't use RetroArch. I'm also using the lastest build from github

**Comment by EgoBizarro** [comment]
Yeah, I could never get it working: https://github.com/rafaelvcaetano/melonDS-android/discussions/558

@Jetup13 so it's actually working for you? And you put the roms just inside of a folder in the MelonDS folder?

**Comment by Jetup13** [comment]
[Here's a video](https://youtu.be/Feu3SuLj7NE).

Like I mentioned it has to be the same folder. So if you added the folder `roms/nds` to Daijishou then you must add that folder to MelonDS. 

Used the latest MelonDS workflow [2b8dcba](https://github.com/rafaelvcaetano/melonDS-android/commit/2b8dcbab77347117fe93655d3374c39c1390eee0)

**Comment by EgoBizarro** [comment]
Ah, yeah, sure, it's the same directory in MelonDS, games are booting fine from inside the emulator and I've got the same version. Strange that it seems to be working for some and not for others...

**Comment by Jetup13** [comment]
Ya I'm not too sure on why it works for some. Maybe Android version? I've tried on Android 9, 11, & 12 and it works as intended.

But like I mentioned, there's the MelonDS Libretro core. Which also supports Retroachievements. Depending of device you might need to enable threaded software rendering

**Comment by EgoBizarro** [comment]
I'm also on Android 12... *shrug*
Oh well, at least it throws me into the emulator, just one more tap then; not perfect but not the end of the world.

**Comment by krtdude** [comment]
Here the fix from the melonDS github page
https://github.com/rafaelvcaetano/melonDS-android/discussions/558#discussioncomment-4795292
