### ISSUE TITLE
Unable to access all available cores for a platform

### ISSUE THREAD

**Issue by virtualsamuraiatgmaildotcom** [magneticchen/Daijishou#189]
Initially I was able to access all cores for a plaftorm in daijisho.
However, i scanned my Final Burn Neo forlder a second time in retroarch.
when i did, All but 3 of the final burn cores dissappeared from daijisho.
To be clear, the cores are still available in retroarch, and function without issue.

I see no clear option to re-link available cores to a platform in daijisho.

**Comment by Jetup13** [comment]
Not following along what you're trying to achieve.

Final Burn Neo platform has [3 selectable cores](https://github.com/magneticchen/Daijishou/blob/main/platforms/FinalBurnNeo.json) by default. (Which is just the Final Burn Neo core but with each Retroarch build).

Are you saying those are not appearing?

**Comment by virtualsamuraiatgmaildotcom** [comment]
Those 3 do appear, and that is great, but I also want other final burn
cores to appear.

Final burn alpha is the core I want. It is available in retoarch, and was
available in daijisho (until I performed a second scan of the final burn
neo rom folder in retroarch)

Not sure how/why a second scan would yield that result, but I would love to
address it.

If there is another way I can make the desired core available I am all ears.

Best Wishes,

Jerad
