### ISSUE TITLE
REQ: Github actions with artifact uploads

### ISSUE THREAD

**Issue by Quackdoc** [magneticchen/Daijishou#19]
Hello, can you enable github actions for commits and pull requests with artifact uploading? 

this is free for all public repos (this is one of them) and has two benefits, it allows users to download the latest builds of the latest commits right from github. and allows automated building (and testing) of any pull requests that might get made. 

thanks in advance for any consideration towards this.

**Comment by magneticchen** [comment]
Hello, thanks for your suggestions. However Daijishō is currently closed source.
