### ISSUE TITLE
New player using Tasker

### ISSUE THREAD

**Issue by MaiconErick** [magneticchen/Daijishou#190]
Hey there. I'm trying to make a player that launcher a task made in Tasker.

This is my code:
```
    -a android.intent.action.VIEW
    -d tasker://assistantactions?task=exampletask
```

It works fine on termux (using "am start" of course) but on daijisho it says that null package was not found on the device.
I also have a Intent Receiver profile on tasker (named startTask) but it shows the same error no matter how I try to make it work on daijisho.

Tasker's package name is: net.dinglisch.android.taskerm

I'm also able to launch the task using am broadcast on termux:

```
am broadcast -a net.dinglisch.android.tasker.ACTION_TASK --es task_name exampleTask
```

**Comment by magneticchen** [comment]
Please check out [Daijishou Console](https://github.com/magneticchen/Daijishou/blob/main/docs/daijishou_console.md) with `\am_start` command. Also do not forget `-n ` argument in your launch command.

**Comment by magneticchen** [comment]
Closed due to inactive. Btw `.dpt` format is introduced for tasker.
