### ISSUE TITLE
Citra enhanced

### ISSUE THREAD

**Issue by Vicv07** [magneticchen/Daijishou#192]
I'm curious if this is missing or if I'm doing something incorrectly. But I have tried every option for 3DS that is not retroarch as I am using the standalone citra enhanced app from retroid pocket. But it will not load the games. I also have citra MMJ and it will work when I've chosen that. But citra MMJ does not have save states so I would prefer to use the enhanced version

**Comment by TheTone82** [comment]
Me too

**Comment by magneticchen** [comment]
3DS citra variants are no longer maintained by Daijishou Official.  #121
