### ISSUE TITLE
Support for screenscraper.fr and openretro.org scraping

### ISSUE THREAD

**Issue by stuffu** [magneticchen/Daijishou#194]
Hi

First of all, big thanks for a great frontend!

I’ve set it up the way I want and are looking to have more boxart etc in place.

currently scraping is a hit or miss. I have scraped a lot in my days. Have you considered using https://www.screenscraper.fr/ ? They cover most system and is general a good overall db, but also https://openretro.org/ is best for amiga games and include whdload names as well. Would it be possible to include them or maybe have an option to choose scraper?

**Comment by indiwerwlf** [comment]
I agree on this. I appreciate the scraping feature and how it works. But for example with a series of games on a single platform I often get the same art for all 3.

**Comment by MiguelCardonaG** [comment]
Yeah, I have quite a few games without covers. A cover system like AetherSX2 that allows you to add a URL with the covers would be nice.

**Comment by magneticchen** [comment]
https://www.screenscraper.fr/ only provide french documented APIs. And it is proprietary, their developer side APIs access are acquired forum based and require client to login. Which make it difficult to develop and maintain as free-time dev and a non French speaker.

**Comment by stuffu** [comment]
Oh, didn’t realize that the api documentation was in French. The scraped data is available in English though.

but fully get your point, thanks for looking into it.

**Comment by magneticchen** [comment]
The [feature for scraping via external sources](https://github.com/magneticchen/Daijishou/issues/86) has been added in 1.4.x

**Comment by stuffu** [comment]
Nice, thanks! When can we expect release of 1.4?

**Comment by magneticchen** [comment]
Maybe 1~3 months.

**Comment by stuffu** [comment]
Take your time, you are doing an awesome job!

**Comment by stuffu** [comment]
Nice to see the addition of external scrapers. Is it possible to add openretro.org as external scraper for the Amiga? 

WHDLoad file names does not go well with other scrapers, but openretro has the majority of the WHDLoad file names, making the Amiga platform nice with cover art.

**Comment by magneticchen** [comment]
I will look into openretro.org

**Comment by magneticchen** [comment]
Added.

**Comment by stuffu** [comment]
Awesome! Huge thanks :)

**Comment by stuffu** [comment]
Just checked and I see the tags but can’t find openretro.org as scraping source. Maybe I’m missing something, if libretto: amiga is the source, I guess it still won’t scrape from openretro even with the tags? Anyway, there is nothing added to the games. Huge thanks again!

**Comment by magneticchen** [comment]
Hello. It is included in the DSESS scraper.
https://github.com/magneticchen/Daijishou/blob/main/platforms/CommodoreAmiga.json

**Comment by magneticchen** [comment]
`DSESS:BOX_ART:TAGS(scraperKeyword):https://openretro.org/browse/amiga?q=%7BscraperKeyword%7D&dsess_target_site_selector=div.game_box+a&dsess_target_site=%5E.%2Agame.%2A&&dsess_selector=img.game-cover%5Balt%3D%22front+image%22%5D&dsess_attribute=src&dsess_extractor=%5E%28%5B%5E%3F%5D%2A%29%3F.%2A.%2A`

**Comment by stuffu** [comment]
Hmm strange, if I search for the whdload file name nothing turns up, sorry for getting you into a lot of work. I found this: https://openretro.org/whdload-games

there should be some uuid based search. Not sure if this helps…

**Comment by magneticchen** [comment]
Daijishou is using cutom scraping method called [DSESS](https://github.com/magneticchen/Daijishou/blob/main/docs/dsess.md).  Instead of hashing, since hashing file is very expensive. Also `openretro.org` does support text based searching. Therefore it is compatible with DSESS.

**Comment by stuffu** [comment]
Ok, so there won’t be any possibilities scraping with uuid? I thought uuid was based on file name, text based search.

**Comment by magneticchen** [comment]
Yes. But I am not sure how those `UUID`s are generated. If those are contained in the file. It will involve formatting things that Dai unable to resolve.

**Comment by stuffu** [comment]
Did some research on this, apparently there is a match while scraping to a db https://github.com/BlitterStudio/amiberry/wiki/Structure-of-the-whdload_db.xml-file

One scraper using this
https://github.com/muldjord/skyscraper/blob/master/src/openretro.cpp

If it's too much work, just say. I'm happy that you tried! It's just that Amiga games are often WHDLoad, and have odd names, resulting in no hits when scraping.

**Comment by magneticchen** [comment]
That will be to much of work. :/

You can use Skraper now btw.
