### ISSUE TITLE
Easier Import Platforms

### ISSUE THREAD

**Issue by Retro-Devils** [magneticchen/Daijishou#2]
Issue you wanna import emus . I think this is achievable by saving all those Pegasus converter files as examlesystem.txt files . Then including them in a folder and then you can load in app directly . 

I tested this with a Pegasus Metadata renamed to atari.txt just now worked fine.

**Comment by magneticchen** [comment]
Hello.  I am actually start working on it by let it able to share platform first. I need to step after steps to implement it properly. After implemented platform sharing. I will introduce a feature to download selected platforms that predefined on this GitHub page. The launcher will automatically fetches newest available platforms and show the checkbox list without needs to updating the app itself.

**Comment by MonkoftheFunk** [comment]
I was going to add, perhaps some preset platforms and players on install for jump in and go, then advance users can customize. Love your above plans though!

**Comment by magneticchen** [comment]
Started from version 37 (1.1.11). Now you can import platforms from this GitHub repo directly in the app.

**Comment by magneticchen** [comment]
Started from version 37 (1.1.11). Now you can import platforms from this GitHub repo directly in the app.

**Comment by Retro-Devils** [comment]
Awesome !!!

**Comment by magneticchen** [comment]
Hello. I've seen that you forked the repo. I want to inform you that started from version 50 (1.1.24). You can set custom platform index json uri. Thus you can test out your own repo for platforms downloading/importing. Good luck!

**Comment by Retro-Devils** [comment]
Awesome that will make everything g for summoning so much easier. 
One issue howd you generate the index.json for the github ?
