### ISSUE TITLE
Request: Show disc index of ROMs in Game List

### ISSUE THREAD

**Issue by GumbyXGames** [magneticchen/Daijishou#20]
Can you add an option to set a custom name in the game list for a ROM? For example I have Shenmue 2 on my device and it is on four disks. Currently there is no way to know which disk is which on the games list as they all show up as **Shenmue II**. 

I have changed the _playable item name_ and disabled _Scrape and replace name_ but all disks are still listed as **Shenmue II**

**Comment by magneticchen** [comment]
Hello. I've tried to change the item name and it works here is the footage of changing name of it.
https://user-images.githubusercontent.com/22817012/168297003-fe60c766-e06c-4fef-bdc4-ad1dfe580b0d.mp4

**Comment by GumbyXGames** [comment]
I am trying to get extra text in the game/entry title such as the disc number. To use your video as an example, I was trying to get "Shenmue 2 (Disc 3)" to display so I can easily tell which "Shenmue 2" in the list is Disc 1, Disc2 etc.

**Comment by magneticchen** [comment]
You can disable prettify title in order to show discs.
![Screenshot_20220514-144356](https://user-images.githubusercontent.com/22817012/168414288-237698e9-7996-45b3-b8e7-8813b6c0e521.png)

**Comment by GumbyXGames** [comment]
I missed that setting. Sorry.

**Comment by magneticchen** [comment]
No problem. Mate
