### ISSUE TITLE
Sync'ing does not remove no longer existing entries

### ISSUE THREAD

**Issue by bsturk** [magneticchen/Daijishou#203]
I delete files and do a re-sync and they still show up in the menu, and give an exception when launching.  I tried unlinking and re-syncing and I don't get an exception, just a popup that says "This item has an empty URI, please resynchronize"

**Comment by Jetup13** [comment]
If you haven't figured it out: `Daijishou > Settings > Clear all disjointed items on sync`. 

This should remove items that Daijishou can no longer find after syncing

**Comment by bsturk** [comment]
I hadn't found it, so thank you.  It worked perfectly!
