### ISSUE TITLE
Retroarch freezes/crashes when opening SNES games from Daijishou

### ISSUE THREAD

**Issue by makedir** [magneticchen/Daijishou#208]
When I open any SNES games, from Daijishou, it opens Retroach but it crashes just with black screen. Opening Retroach directly works fine loading SNES games. It is 1.14 stable, on Android 13 with a Samsung M23 phone. I use bsnes-hd beta as core for SNES in Retroarch.

When you press play for any SNES game in Daijishou it says "killing package processes", if you hit confirm, it opens Retroach and it freezes with black screen.

**Comment by Dans-Droids** [comment]
I have the same issue on Teclast P80x running Android 9, black screen then Retroarch Plus crashes..

**Comment by magneticchen** [comment]
Does your player correctly select in daijishou SNES platform settings(As you mentioned that you are using bsnes-hd core).

**Comment by makedir** [comment]
Thanks that actually solved the problem. It was set to snes9x, I have switched to bsnes_hd_beta and now it works. I found another but that if you init the app for the first time and select a few platform, there is a java exception error shown when it downloads the platforms.
