### ISSUE TITLE
MD5 hashes with .gdi files

### ISSUE THREAD

**Issue by GumbyXGames** [magneticchen/Daijishou#21]
It seems like the regular express for _Accepted Filename_ is not working as expected. Using the default regex some of my games are missing and some of the extensions I add to the expression does not take. 

Example

File structure
```
Dreamcast
|->Cannon Spike (USA) 
  |>Cannon Spike (USA) (Track 1).bin
  |>Cannon Spike (USA) (Track 2).bin 
  |>Cannon Spike (USA) (Track 3).bin
  |>Cannon Spike (USA).gdi
|>Illbleed (USA) 
  |>Illbleed v1.002 (2001)(AIA)(NTSC)(US)[!].gdi
  |> track01.bin
  |> track02.raw
  |> track03.bin
|> Power Stoner 2 (USA) 
  |> Power Stone 2 v1.000 (2000)(Capcom)(NTSC)(US)[!].gdi
  |> track01.bin
  |> track02.raw
  |> track03.bin
|>Dreamcast.backup.dat
```

Accepted filename regex: ```^(?! (? :\. _|\.).*).*(?<!bin)(?<!iso)(?<!raw)(?<!dat)$```

Resulting Games List:
Cannon Spike
Dreamcast.backup

Expected Games List:
Cannon Spike
Illbleed
Power Stone 2

I tested the regex at regex101.com and it works with those filenames.

**Comment by magneticchen** [comment]
Hello you can try to use the whitelist regex below


^(?!(?:\._|\.).*).*(?<!bin|gdi)$

**Comment by GumbyXGames** [comment]
Nothing shows up in the game list now

**Comment by GumbyXGames** [comment]
> Ah soooory. I used black list regex which is wrong.
> 
> This one(whitelist) should work.
> 
> `^(?!(?:\._|\.).*).*gdi$`
> 
> Or this one(blacklist)
> 
> `^(?!(?:\._|\.).*).*(?<!bin|iso|raw|dat)$`

Sadly neither worked. I getting the game list I originally got.

**Comment by magneticchen** [comment]
How about the whitelist one? Thanks.

**Comment by GumbyXGames** [comment]
> How about the whitelist one? Thanks.

I did and but got got the same results as the blacklist: Cannon Spike is the only game to show up and the Dreamcast.backup file doesn't come up.

**Comment by magneticchen** [comment]
Hmmm. That is weird. 🤔

**Comment by GumbyXGames** [comment]
Just came across something.  When I have the file structure, the Illbeed GDI file name shows up under the scraper keywords for Virtua Fighter 3tb:

File structure
```
Dreamcast
|->Cannon Spike (USA) 
  |>Cannon Spike (USA) (Track 1).bin
  |>Cannon Spike (USA) (Track 2).bin 
  |>Cannon Spike (USA) (Track 3).bin
  |>Cannon Spike (USA).gdi
|>Illbleed (USA) 
  |>Illbleed v1.002 (2001)(AIA)(NTSC)(US)[!].gdi
  |> track01.bin
  |> track02.raw
  |> track03.bin
|> Power Stoner 2 (USA) 
  |> Power Stone 2 v1.000 (2000)(Capcom)(NTSC)(US)[!].gdi
  |> track01.bin
  |> track02.raw
  |> track03.bin
|>Dreamcast.backup.dat
|> Virtua Fighter 3tb (USA)
  |> track01.bin
  |> track02.raw
  |> track03.bin
  |> Viruta Fighter 3tb v1.002 (1999)(Sega)(NTSC)(US)[!].gdi
```

**Comment by magneticchen** [comment]
Hmmm. So after you added virtual fighter. All gdi files showed up?

**Comment by GumbyXGames** [comment]
No. The GDI file names showed up as scraper keywords. The files do not show up in the game list.

**Comment by magneticchen** [comment]
I understand what's happening now. Probably because those gdi files has same hashes. Daijishō merge those files into a single game. Thus regex is actually working. But the same hashes make those file merged together.

**Comment by magneticchen** [comment]
Hello. I've inspected my own dreamcast collection. For example:
![image](https://user-images.githubusercontent.com/22817012/168810867-54f63bfb-a262-42ac-b315-ba5d2fba0e83.png)
And the .gdi file opened by text editor is like:
`
21
 1      0 4 2352 "Reel Fishing + Wild (USA) (Track 01).bin" 0
 2   5375 0 2352 "Reel Fishing + Wild (USA) (Track 02).bin" 0
 3  45000 4 2352 "Reel Fishing + Wild (USA) (Track 03).bin" 0
 4 266479 0 2352 "Reel Fishing + Wild (USA) (Track 04).bin" 0
 5 271946 0 2352 "Reel Fishing + Wild (USA) (Track 05).bin" 0
 6 281165 0 2352 "Reel Fishing + Wild (USA) (Track 06).bin" 0
 7 292119 0 2352 "Reel Fishing + Wild (USA) (Track 07).bin" 0
 8 303214 0 2352 "Reel Fishing + Wild (USA) (Track 08).bin" 0
 9 313998 0 2352 "Reel Fishing + Wild (USA) (Track 09).bin" 0
10 323975 0 2352 "Reel Fishing + Wild (USA) (Track 10).bin" 0
11 335050 0 2352 "Reel Fishing + Wild (USA) (Track 11).bin" 0
12 346376 0 2352 "Reel Fishing + Wild (USA) (Track 12).bin" 0
13 356515 0 2352 "Reel Fishing + Wild (USA) (Track 13).bin" 0
14 367231 0 2352 "Reel Fishing + Wild (USA) (Track 14).bin" 0
15 380789 0 2352 "Reel Fishing + Wild (USA) (Track 15).bin" 0
16 389376 0 2352 "Reel Fishing + Wild (USA) (Track 16).bin" 0
17 401058 0 2352 "Reel Fishing + Wild (USA) (Track 17).bin" 0
18 413479 0 2352 "Reel Fishing + Wild (USA) (Track 18).bin" 0
19 423898 0 2352 "Reel Fishing + Wild (USA) (Track 19).bin" 0
20 435468 0 2352 "Reel Fishing + Wild (USA) (Track 20).bin" 0
21 447906 4 2352 "Reel Fishing + Wild (USA) (Track 21).bin" 0
`
Which naturally generate different MD5 checksum. You can manually modify them to make it works.

**Comment by GumbyXGames** [comment]
> Hello. I've inspected my own dreamcast collection. For example: ![image](https://user-images.githubusercontent.com/22817012/168810867-54f63bfb-a262-42ac-b315-ba5d2fba0e83.png) And the .gdi file opened by text editor is like:
> 
> ```
>  1      0 4 2352 "Reel Fishing + Wild (USA) (Track 01).bin" 0
>  2   5375 0 2352 "Reel Fishing + Wild (USA) (Track 02).bin" 0
>  3  45000 4 2352 "Reel Fishing + Wild (USA) (Track 03).bin" 0
>  4 266479 0 2352 "Reel Fishing + Wild (USA) (Track 04).bin" 0
>  5 271946 0 2352 "Reel Fishing + Wild (USA) (Track 05).bin" 0
>  6 281165 0 2352 "Reel Fishing + Wild (USA) (Track 06).bin" 0
>  7 292119 0 2352 "Reel Fishing + Wild (USA) (Track 07).bin" 0
>  8 303214 0 2352 "Reel Fishing + Wild (USA) (Track 08).bin" 0
>  9 313998 0 2352 "Reel Fishing + Wild (USA) (Track 09).bin" 0
> 10 323975 0 2352 "Reel Fishing + Wild (USA) (Track 10).bin" 0
> 11 335050 0 2352 "Reel Fishing + Wild (USA) (Track 11).bin" 0
> 12 346376 0 2352 "Reel Fishing + Wild (USA) (Track 12).bin" 0
> 13 356515 0 2352 "Reel Fishing + Wild (USA) (Track 13).bin" 0
> 14 367231 0 2352 "Reel Fishing + Wild (USA) (Track 14).bin" 0
> 15 380789 0 2352 "Reel Fishing + Wild (USA) (Track 15).bin" 0
> 16 389376 0 2352 "Reel Fishing + Wild (USA) (Track 16).bin" 0
> 17 401058 0 2352 "Reel Fishing + Wild (USA) (Track 17).bin" 0
> 18 413479 0 2352 "Reel Fishing + Wild (USA) (Track 18).bin" 0
> 19 423898 0 2352 "Reel Fishing + Wild (USA) (Track 19).bin" 0
> 20 435468 0 2352 "Reel Fishing + Wild (USA) (Track 20).bin" 0
> 21 447906 4 2352 "Reel Fishing + Wild (USA) (Track 21).bin" 0
> ```
> 
> Which naturally generate different MD5 checksum. You can manually modify them to make it works.

I have a much of dreamcast games that puts hands to edit. Sadly I won't be able to use this front-end
