### ISSUE TITLE
Retro achievments game title null

### ISSUE THREAD

**Issue by RoyceAscari** [magneticchen/Daijishou#215]
Just recently everytime i go to check my achievments, the game titles read null, and when clicking on a game. The title simple just doesnt appear. Its strange because when you restsrt the app and click on achievements everything is normal, but one by one over a couple seconds they all go to null. It could be connected to the fact that i had deleted some pictures from a games achievments because i uninstalled that game and didnt want those pictures in my gallery. But ive done that in the past with no problems
![Screenshot_20230209-230205_Daijish](https://user-images.githubusercontent.com/125001742/218035765-f970ce38-2875-4daf-9df4-e7d7742ff441.jpg)
![Screenshot_20230209-230131_Daijish](https://user-images.githubusercontent.com/125001742/218035773-fc2a467d-628f-46f3-8db1-b6d7fd36e238.jpg)
![Screenshot_20230209-230140_Daijish](https://user-images.githubusercontent.com/125001742/218035778-b9659726-e885-400b-be53-185bfd0277bf.jpg)

**Comment by Jetup13** [comment]
[RetroAchievements API](https://github.com/RetroAchievements/RAWeb) seems to have updated recently which would explain the null error. This will most likely need to be updated on Daijishou

**Comment by magneticchen** [comment]
Thanks for the report. App has been updated and changes are included in the newest version.
