### ISSUE TITLE
Feature request: delete rom

### ISSUE THREAD

**Issue by Txori** [magneticchen/Daijishou#217]
When there's a game that I don't like at all, I remove the file for good. So right now, I'm switching from Daijishou to a file explorer in order to do that.
Could it be possible to add a button, maybe next to "Unlink ROM" in order to delete the rom file?

**Comment by magneticchen** [comment]
#152

**Comment by Txori** [comment]
Sorry, but deleting the rom file isn't the same as #152 hiding rom entries in the list.

**Comment by magneticchen** [comment]
You mean to completely delete the ROM file in the file system?

**Comment by Txori** [comment]
Hahaha yes. I don't want to see the Olsen twins GBA game when refreshing the rom list. Buy I understand this might be an authorization problem with Android 11. No worries.

**Comment by magneticchen** [comment]
Now, I understood. However, I Daijishou will never touch your file system for now. Daijishou is following write protect policy to your games. (I previous messed up and delete user's files in the very early stage of Daijishou, due to SAF stuffs, so I gave up managing files externally)
