### ISSUE TITLE
Feature request: multiple box art aspect ratios for single system.

### ISSUE THREAD

**Issue by MisterIkkus** [magneticchen/Daijishou#219]
The only thing I dislike about Daijisho is that it forces all box art into a single aspect ratio for every system. This is okay for some systems, but for SNES, for example, Japanese box art is a very different aspect ratio than US box art. Currently, Daijisho just shows the middle of the Japanese box art in the aspect ratio of the US box art, cutting off the top and bottom.

It would be great if Daijisho would support these kind of box art aspect ratio differences for each system.

Thanks.

**Comment by magneticchen** [comment]
Sorry, this suggestion has been requested previously. However, due to how Android handle aspect ratio and dpad support. The request can not be full-fill efficiently. And can break support for various devices in range. Therefore it is rejected.

**Comment by MisterIkkus** [comment]
Understandable. Thanks for letting me know.
