### ISSUE TITLE
"rom format is invalid" while trying to run 3ds games 

### ISSUE THREAD

**Issue by SiegfreedOs** [magneticchen/Daijishou#22]

**Comment by SiegfreedOs** [comment]
Just downloaded the app today and really liked it but whenever i try to open any 3ds game i get kicked out to the app.

**Comment by denisidoro** [comment]
I don't think that's related to Daijishou. See https://github.com/weihuoya/citra/issues/540

**Comment by SiegfreedOs** [comment]
oh i see, i'll try using the non storage access version and tell the results, really hope it goes right since of all front-ends so far this has showed to be the most well polished and good looking ones.

**Comment by SiegfreedOs** [comment]
oh it did, thanks man, you really made my day, the only issue concerning the front-end right now is with the saturn games since yaba sanshiro installs the games on the data directory and i can't seem to access the folders both in the sd card and internal storage, any idea of what i can do?
