### ISSUE TITLE
Duplicated games after scrapping

### ISSUE THREAD

**Issue by dannygaray60** [magneticchen/Daijishou#220]
Samsung A12 - Android 13

When I make scrap, there are some duplicated games
![Screenshot_20230212_104120_Daijish](https://user-images.githubusercontent.com/30391210/218345002-c6baa3fa-f8ea-4019-ba66-96c93dd342d4.png)
But they duplicates point to the same rom file:
![Screenshot_20230212_104147_Daijish](https://user-images.githubusercontent.com/30391210/218345019-88ab7288-3780-4ee1-8d11-7f24853651bf.png)
![Screenshot_20230212_104132_Daijish](https://user-images.githubusercontent.com/30391210/218345021-6bf5a8dc-1d75-48f5-a6db-11c0ccbf14cc.png)
The duplicates have different md5 but they point to the same file
And there no duplicated files in filesystem:
![Screenshot_20230212_104223_MiXplorer](https://user-images.githubusercontent.com/30391210/218345052-6e580a91-70ac-4651-92b7-0b9b18534fab.png)

**Comment by MiguelCardonaG** [comment]
Si no estoy equivocado, tienes 2 rom de Super Mario Bros 2 (original + mod) y 2 más de SMB 3 (igual que la anterior). Pues yo lo veo correcto que te salgan dobles en Daijishō. 🤔

**Comment by magneticchen** [comment]
Please delete and try again. Or check the delete disjoint items on sync option in settings.

**Comment by dannygaray60** [comment]
@magneticchen is the same result, I disjointed the items, then deleted, and when turn sync option, the duplicateds appears again

**Comment by magneticchen** [comment]
I am completely not idea everything the same but only md5 hashes ar different. Does it happen everywhere or only this particular file.

**Comment by Post-Mortem** [comment]
@magneticchen something similar happened to me, i have a hacked rom file of megaman x6, only one file, but it shows up twice on daijisho.

**Comment by magneticchen** [comment]
@dannygaray60 would you mind send me the roms copy to me on dc?

**Comment by magneticchen** [comment]
![telegram-cloud-photo-size-5-6077703398054016205-y](https://user-images.githubusercontent.com/22817012/224354839-559727da-e500-4c2d-bee8-4fc6d626c822.jpg)
Delete correct entry or both entries will fix that. Next version of Dai will check different md5 with same path.

**Comment by dannygaray60** [comment]
solved! thanks
