### ISSUE TITLE
Not Syncing ROMS on S22U

### ISSUE THREAD

**Issue by mj4920** [magneticchen/Daijishou#224]
ROMS won't sync on any platform on S22U (snapdragon variant). Working perfectly on Note 10+

Regex is set to accept all file types. ROMS are same files used in both cases. Game path set exactly the same and selected 

UPDATE: Problem was not with Daijisho. Was having same problem with other front ends and emulators. Was only able to fix by factory resetting the phone.

**Comment by magneticchen** [comment]
Can you explain more explicitly. Are other platforms syncing your files as well.

**Comment by mj4920** [comment]
Please disregard. Updated my original comment. Fixed by factory resetting phone. Thank you for your response though.
