### ISSUE TITLE
Platform title is currently shown 3 times on screen.

### ISSUE THREAD

**Issue by unbelievableflavour** [magneticchen/Daijishou#230]
As you can see in this image, by default the application shows the platform title 3 times. 

The titles surrounded by a green line are OK and are actually useful. Though the one surrounded by red (the one with the icon) offers no extra information and only clutters the screen. It (and also the icon) can just be removed.

![image0](https://user-images.githubusercontent.com/3491721/220400641-acbaac57-7842-4fb4-9175-b5d76b4dcf98.png)

**Comment by magneticchen** [comment]
I am aware of this. But I can't come up with a better decoration on screen. (For larger aspect ratio and tablet screens)

**Comment by lukecharman** [comment]
Do you need a decoration? Sometimes, less is more :)

**Comment by unbelievableflavour** [comment]
Completely agree with luke charman. The decoration does not give any more clearity to the user. Adding a single consistent location will only make it easier for the user to read. Also since the icon is the same for every platform, it is also not necessary. to add the icon there.

**Comment by magneticchen** [comment]
I did simplified 1.4.x UI a bit. I will consider your suggestion when available. (It really looks kidda awkward on larger screen without additional text to me).

![image](https://user-images.githubusercontent.com/22817012/220956995-d9305c47-d454-41e5-965c-1c5dc025f9a2.png)

**Comment by unbelievableflavour** [comment]
Can you show me what you mean by awkward? Because I do not see it. Or havent seen daijisho on a larger screen.

**Comment by magneticchen** [comment]
Since I've migrated my desktop operating system. Previously set-up android tablet emulators are no longer present. So, I cannot show you directly.
Here, however is an [example](https://youtu.be/DmCT10bb9xw?t=319) on ETA Prime's video.

At the end. I am open to the suggestions, and appreciate it. But I will make my own aesthetic decision.

**Comment by magneticchen** [comment]
Ok. Since the scale UI option has been introduced. I think it actually to point to keep that for tablet support. And It does look better and clear. I've removed the shortname.
