### ISSUE TITLE
Option to disable the border + side-margin

### ISSUE THREAD

**Issue by unbelievableflavour** [magneticchen/Daijishou#234]
Currently in the homescreen there is a giant border with some margin left and right. I personally feel this border is something that should be stylable or an option to disable it. It can give a lot of themers a more different canvas which makes it feel just a little more customizable.

Basic theme example:
Before:
![Screenshot_20230222-140744](https://user-images.githubusercontent.com/3491721/220628414-cecc9fc2-0793-474a-9d2f-84d1ce55a670.png)

After:
![Screenshot_20230222-140744](https://user-images.githubusercontent.com/3491721/220629221-6035cca2-dd51-41dc-b94b-b2b1b83e64f8.png)

And for other themes it looks better as well:
Before:
![Screenshot_20230222-132115 (2)](https://user-images.githubusercontent.com/3491721/220627929-9947711d-2505-41fd-ad74-6d41981440c7.png)
After:
![Screenshot_20230222-132115 (1)](https://user-images.githubusercontent.com/3491721/220627925-822c9c07-43a9-437e-a669-6f0ddb5a814a.png)

**Comment by magneticchen** [comment]
Sorry, since I am experimenting new thumbnail/icon mode for platforms. And also due to keeping the consistency of the design language. I am not planing to adopt this change.
