### ISSUE TITLE
Cannot access NAS/SMB ROMs

### ISSUE THREAD

**Issue by f00tf00t** [magneticchen/Daijishou#236]
Hi Team,

As per the title; I can locate, scrape ROMs fromNAS/SMB with no issue and even run these game directly from the emulator but I cannot load the ROMs via the Daijisho Frontend

I attached screenshots to show that I can perform the locatring and scraping from Daijisho, I wanted to know if the issue was a file permissions access issue, as show in the last screenshot.

![001](https://user-images.githubusercontent.com/71181157/220672552-91df8873-a448-4bc9-a3f5-2abcfbb7c2fc.png)

![002](https://user-images.githubusercontent.com/71181157/220672557-6f1290ce-b099-45b6-a8d4-e16aac8fb6df.png)

![003](https://user-images.githubusercontent.com/71181157/220672561-a43234d7-a896-4776-a580-d4db6bb21c64.png)

![004](https://user-images.githubusercontent.com/71181157/220672567-f22990aa-c7aa-4a64-a1f6-af8d12dc3d56.png)

![005](https://user-images.githubusercontent.com/71181157/220672570-5fadad68-dbc2-4995-b09b-8e45d5dbde4c.png)

![006](https://user-images.githubusercontent.com/71181157/220673011-3de25f4b-8843-44bd-8973-c08d53b18648.png)

I ask if its a file access permissions issue as the emulators all request access to read/write files but Daijisho doesn't

**Comment by magneticchen** [comment]
It is because certain emulators do not support Uri Format. Thus, the absolute path is required and generate from daijishō. 
The NAS files therefore can not be used since it has no absolute paths. It is stored in cloud.

**Comment by peerchemist** [comment]
@f00tf00t I was not able to find a way to even locate SMB shares in Daijishou. Can you point me to where did you find that?

**Comment by magneticchen** [comment]
Pure Uri launching is added in the latest version for Uri supported emulators.
