### ISSUE TITLE
add a Korean locale?

### ISSUE THREAD

**Issue by jshsakura** [magneticchen/Daijishou#238]
Hello, I am a fan of Daijishou and I love this project.
I wanted to add a Korean locale to Daijishou.

I don't see a separate locale file in the source.
Now it seems that multi -language is applied only to search.

Can I get a template to add Korean to the supported languages?
Or do you have plans to apply in the future?

**Comment by magneticchen** [comment]
Hello, of course. Since I am working on 1.4 update. The locale is currently changing. Would you mind waiting until 1.4 is finished (it takes months). Also it is welcome to join our [discord](https://discord.com/invite/nJbxdT3QQE). There is a development channel to discuss related topics. Thanks.

**Comment by jshsakura** [comment]
Thank you for your enthusiasm.
I will come back with version 1.4 and join the Discord channel.

**Comment by magneticchen** [comment]
Thanks 🙏

**Comment by magneticchen** [comment]
Hello. Thanks for the patient waiting. Now 1.4. has been on stable stage.
Please contact me on discord if you still want to implement Korean language. Thank you!

**Comment by jshsakura** [comment]
good~!
I am very poor at English, but I think I can overcome it.
I'll have to mobilize Google Translate, but I'll find it on Discord.

**Comment by magneticchen** [comment]
Added in `1.4.7`
