### ISSUE TITLE
Cannot add BIN games to Naomi folder, even with edited regex

### ISSUE THREAD

**Issue by LoSmarrito** [magneticchen/Daijishou#243]
Hi, 
just as the title says, even if I edit the regex string I cannot add .bin games to the frontend inside the Naomi category (flycast does support BIN files).

If I apply the same regex string to the same folder inside the Atomiswave section, these games are recognized.

**Comment by Jetup13** [comment]
1. Your using an outdated romset if your using bin files for `naomi` or `atomiswave`. Those need to be loaded with a `.lst` file. Highly would recommend to switching to a MAME romset. 
2. If you want add bin: Highlight Platform > 🖊️ > Select the player bubble below player settings > Edit > Save

**Comment by LoSmarrito** [comment]
Understood, thank you
