### ISSUE TITLE
PPSSPP bug screen crop

### ISSUE THREAD

**Issue by AgentlReal** [magneticchen/Daijishou#249]
Whenever i run a game via daijishō, the game will always get cropped in the corner. Bit If i ran it via PPSSPP manually, i wouldn't face the problem. It happens to all games, for example: Spider-Man 2 2![Screenshot_2023-02-25-05-04-19-110_com.magneticchen.daijishou.jpg](https://user-images.githubusercontent.com/114266724/221302476-d1adb081-ec84-4dc6-80a9-4091c0ad364c.jpg)![IMG_20230225_050749.jpg](https://user-images.githubusercontent.com/114266724/221302906-6b0a6640-c290-4f43-bbad-06326a48b306.jpg)![IMG_20230225_050903.jpg](https://user-images.githubusercontent.com/114266724/221302937-d21738da-0174-4e78-b7e8-1207c57ccf3a.jpg)

**Comment by ghiki** [comment]
It's RA core  or standalone? Strange, I haven't this problem in PPSSPP 1.12.3 with Daijisho 1.3.43

**Comment by AgentlReal** [comment]
> It's RA core  or standalone? Strange, I haven't this problem in PPSSPP 1.12.3 with Daijisho 1.3.43

I don't understand what RA core or standalone means, but my PPSSPP version is 1.14.4 and Daijishō 1.3.43. The problem is still occurring and I haven't found the solution.

**Comment by magneticchen** [comment]
#179

**Comment by squadz3** [comment]
Sharing that I'm having the exact same issue. Ppsspp 1.14.4, daijisho 1.4.6
