### ISSUE TITLE
Gray buttons have white text in dark mode

### ISSUE THREAD

**Issue by denisidoro** [magneticchen/Daijishou#25]
![Screenshot_2022-05-08-14-24-07-980_com magneticchen daijishou](https://user-images.githubusercontent.com/3226564/167519161-a0c8d987-c429-4927-a4cf-66c09896a6cd.jpg)

**Comment by denisidoro** [comment]
Please check the pencil + select + back buttons

**Comment by magneticchen** [comment]
Hey I've checked it on my devices and ask ppl in the discord group for the issues. And I couldn't reproduce the problem.
It might be the same problem occurred by this dude. Here is the link.
https://t.me/daijishou/164

And here is mine dark theme.
![Screenshot_20220513-213137](https://user-images.githubusercontent.com/22817012/168295399-1efe6fc7-275b-4e8b-a776-278410c3b05c.png)

**Comment by magneticchen** [comment]
Another ppl has the same problem. Caused by MIUI.

https://t.me/daijishou/1376
