### ISSUE TITLE
关于语言问题

### ISSUE THREAD

**Issue by xrain0610** [magneticchen/Daijishou#252]
如何才能切换语言?  似乎现在是跟随系统语言选项, 能否提供一个方式,可以允许我们添加语言?

**Comment by magneticchen** [comment]
Sorry. Daijishou follows Android standard implementation, which means language files are hardcoded statically. Thus dynamic injection is not possible. To switch language, change your android OS language settings or use the Android 13 per app lang-settings feature. BTW, I might added Simplified Chinese when I have free time after 1.4.x update.

Below are the limited languages currently be maintained:

English
Portuguese
Taiwanese mandarin 
Japanese
French
Italian
Spanish
