### ISSUE TITLE
Daijishō It has no support for the emulator Nostalgia.gg

### ISSUE THREAD

**Issue by MiguelCardonaG** [magneticchen/Daijishou#266]
I want to start Sega Game Gear games from Daijishō and the emulator version is not available NOSTALGIA.GG Pro.

Please add it.

https://play.google.com/store/apps/details?id=com.nostalgiaemulators.ggfull

**Comment by LeDechaine** [comment]
Hi. Nostalgia.nes, Nostalgia.gba and Nostalgia.gbc doesn't seem to be detected either. I don't know if I should open another issue.
