### ISSUE TITLE
Android asks for the default launcher after restart.

### ISSUE THREAD

**Issue by Post-Mortem** [magneticchen/Daijishou#273]
Whenever i turn off and then on my device (RP2+) it asks if i want to make Daijisho my default launcher, i click on 'always' . If i turn off the device and then turn it on it will ask again for the default launcher. This only happens on 1.4.

**Comment by magneticchen** [comment]
Are you able to enter Daijishō app itself and screenshot error from the logger?

**Comment by Post-Mortem** [comment]
![Screenshot_20230303-173639](https://user-images.githubusercontent.com/110559167/222834169-04792127-83d2-4a44-b667-769ae013838d.png)
![Screenshot_20230303-173716](https://user-images.githubusercontent.com/110559167/222834194-fa5f2052-ca47-4542-b3c2-1e5e9dc7a1f9.png)
![Screenshot_20230303-173726](https://user-images.githubusercontent.com/110559167/222834205-3625729c-5dc6-427b-803c-924de4b3753c.png)

here you go

**Comment by magneticchen** [comment]
Can you screenshot the part flagged as error (Red one)

**Comment by magneticchen** [comment]
Here is an example:

![IMG_20230304_055522_461.png](https://user-images.githubusercontent.com/22817012/222836979-d0c5a755-55df-411d-83ce-0d7f436b4204.png)

**Comment by Post-Mortem** [comment]
Hmm I enabled debug mode and I couldn't find any error. I Believe the app is not crashing. Is just that is not being saved as the default launcher. Even though I press the "always" button.

**Comment by magneticchen** [comment]
Hmm that's weird. Also mentioned that if the app crashed. The default launcher settings will be wiped out.

**Comment by Post-Mortem** [comment]
Does it happen on your device? I'm using it on a RP2+. The setting will be saved until I turn off or restart the device.

**Comment by magneticchen** [comment]
> Does it happen on your device? I'm using it on a RP2+. The setting will be saved until I turn off or restart the device.

No. I have tested it on my RP2+.

**Comment by Post-Mortem** [comment]
The first time I installed the beta it said that the app was not verified by the playstore and whatever. Maybe the playstore is preventing it from saving it as default? The weird thing is that it stays as the default app until I reset the rp2+

**Comment by magneticchen** [comment]
> The first time I installed the beta it said that the app was not verified by the playstore and whatever. Maybe the playstore is preventing it from saving it as default? The weird thing is that it stays as the default app until I reset the rp2+

I've never countered this situation. It might be the reason. Thanks for the report bro.

**Comment by Post-Mortem** [comment]
Anytime brother. 👌

**Comment by Post-Mortem** [comment]
The issue seems to haven been solved but know I'm getting this persistent notification. 
![Screenshot_20230306-174356](https://user-images.githubusercontent.com/110559167/223241476-450ac238-156a-4a5b-8d81-33811ae31292.png)

**Comment by magneticchen** [comment]
Okay this means that it is not the timeout causing the issue. But your Android system is limiting background service. New RCs have added foreground roll back to fix this issue.

**Comment by Post-Mortem** [comment]
Awesome dude. I don't mind the notification if that means DAI is working properly :D. Any idea why this didn't happen before 1.4?

**Comment by magneticchen** [comment]
> Awesome dude. I don't mind the notification if that means DAI is working properly :D. Any idea why this didn't happen before 1.4? 

Because the daijishō service is introduced only on 1.4. 👍😬

**Comment by Post-Mortem** [comment]
Oooh cool ,cool 👌
