### ISSUE TITLE
1.4 rc1 asks for Google drive account 

### ISSUE THREAD

**Issue by Post-Mortem** [magneticchen/Daijishou#276]
I don't know if this is intended but as soon as I updated the app it started to ask me for my Google account. I close the window but it shows up over and over again. Also, the option to disable automatic backup is greyed out in the settings.

**Comment by Post-Mortem** [comment]
![IMG_20230304_160907](https://user-images.githubusercontent.com/110559167/222926620-3f44578b-589c-49e4-9b82-e1bf44c76b00.jpg)

**Comment by magneticchen** [comment]
Fixed in RC2
