### ISSUE TITLE
Italic font style causing cutout

### ISSUE THREAD

**Issue by MiguelCardonaG** [magneticchen/Daijishou#282]
![20230307_084838](https://user-images.githubusercontent.com/65356692/223358421-c206e76c-7f92-4a28-a0aa-bad9436ea519.jpg)

I have the latest version available [v1.4.0-rc8].

**Comment by magneticchen** [comment]
Please try to remove custom fonts.

**Comment by MiguelCardonaG** [comment]
Where is that option? 😅

**Comment by MiguelCardonaG** [comment]
I have put the standard font and it seems that it is solved:

![Screenshot_20230307_121938](https://user-images.githubusercontent.com/65356692/223407908-984c3bbb-130f-47e8-bea5-99373c773a59.jpg)

But still, the letters are still cut a bit. By the way, why does the font come out in italic format? If they were in straight format that would not happen.

Is it solved by adding a blank space at the end of the text?

**Comment by magneticchen** [comment]
> But still, the letters are still cut a bit. By the way, why does the font come out in italic format? If they were in straight format that would not happen.
Italic for format is for aesthetic and for distinguishing tile.

> Is it solved by adding a blank space at the end of the text?
No. It is solved by setting singleLine to "true".

**Comment by MiguelCardonaG** [comment]
And this? No fix?
