### ISSUE TITLE
I can't disable the 'widgets' or 'highlights' tabs

### ISSUE THREAD

**Issue by MSB218** [magneticchen/Daijishou#283]
I'd like to be able to disable these, as I don't use them; I used to be able to disable 'widgets', but I just updated and can't find an option to do so now. Thank you!

**Comment by magneticchen** [comment]
Hello this option have been disabled in 1.4.

**Comment by magneticchen** [comment]
If you are on 1.4.2 please check out [Daijishou Console](https://github.com/magneticchen/Daijishou/blob/main/docs/daijishou_console.md).
