### ISSUE TITLE
Daijishō crashes frequently in 1.4.

### ISSUE THREAD

**Issue by MiguelCardonaG** [magneticchen/Daijishou#286]
![Screenshot_20230308-175111_Device care](https://user-images.githubusercontent.com/65356692/223777386-cd151879-983b-41c7-afd5-04280328b470.jpg)

I have a lot of frequent errors since I installed the latest version, with the previous version there were no such errors.

**Comment by magneticchen** [comment]
Which version are you using?

**Comment by MiguelCardonaG** [comment]
![Screenshot_20230308-180107_Daijish](https://user-images.githubusercontent.com/65356692/223779776-3e8de032-c092-4959-a33a-7da385976240.jpg)

**Comment by magneticchen** [comment]
Can you open the logger and check if there is any errors. (The one with red prohibit icon)

**Comment by MiguelCardonaG** [comment]
This?

![Screenshot_20230308-180835_Daijish](https://user-images.githubusercontent.com/65356692/223781421-d5e8d8bb-faa7-4e2a-b932-3c39a8f9d86e.jpg)

**Comment by magneticchen** [comment]
Yes but the one with red prohibit icon and error tag.

**Comment by magneticchen** [comment]
![image](https://user-images.githubusercontent.com/22817012/223784627-ceffc259-f94e-4196-a539-8e03fa2cc8a6.png)

**Comment by MiguelCardonaG** [comment]
There is no red one, they are all ⚠️

**Comment by magneticchen** [comment]
Thanks for the report. Please leave debug mode **on** to record the succeeding crashes, or have to wait for the future update to possibly fix the crash. Thanks.

**Comment by magneticchen** [comment]
Closed due to no further reports.  Maybe the crashes have been mitigated.
