### ISSUE TITLE
Favorites, Recents, and New Links are Now Broken

### ISSUE THREAD

**Issue by saskwatch** [magneticchen/Daijishou#288]
![Screenshot_20230309_120815_Daijish](https://user-images.githubusercontent.com/3989240/224104216-fd91da5a-d806-479e-a488-c0e15d3b8f11.jpg)

When clicking Favorite, Recent, or New, it would take you to the Highlight tab and only show the Favorites , Recents, or New items per platform.  Now, it just takes you to what ever the last view of the Highlight page.  There seems to there is no longer filter Favorites, Recents, and New Items by platform - which was highly useful.  I am using 1.4.5.

![Screenshot_20230309_121036_Daijish](https://user-images.githubusercontent.com/3989240/224105277-4478e25e-f838-4059-b7b3-e3c91749ed6e.jpg)

Also, those buttons on  a Platforms detail  page do nothing.

![Screenshot_20230309_122113_Daijish](https://user-images.githubusercontent.com/3989240/224106618-8a4165e7-9846-47f3-9cc8-ff1d184d7c1d.jpg)

**Comment by magneticchen** [comment]
Yes. I am aware of this. (I will re-add this into platforms page as page, if you click those chip buttons).

**Comment by magneticchen** [comment]
The button will be functional `1.4.7` with different behaviours.

**Comment by magneticchen** [comment]
A note that the highlight page will still shows genres tho. But those button will now work in the different manner.

**Comment by saskwatch** [comment]
This works perfectly now.  Thank you.
