### ISSUE TITLE
Platforms not showing in favorites

### ISSUE THREAD

**Issue by almac7r** [magneticchen/Daijishou#292]
Just updated to latest version and when selecting favorites, platforms has been replaced with genres. Overview shows all favorites across all platforms. Is there a way to display individual platforms under favorites instead of genres? Also, item count on PS2 and SNES shows no items so no favorites button on home page (all roms and highlighted favorites display ok under library) . Carried out sync but still the same. Thanks. PS Daijisho is awesome keep up the good work

**Comment by magneticchen** [comment]
Hello, if there is no items count. It means that you haven't favourites anything things of that platform.

**Comment by almac7r** [comment]
Hi, Yes favorites are showing as highlighted in list mode. There is no item count showing (total number of roms) on platform home screen only for PS2 and SNES, all other platforms showing ok

**Comment by almac7r** [comment]
Hi, Carried out another sync on PS2 and SNES and fixed rom count issue. Just need to know if genres can be replaced with individual platforms under the favorites section as all favorites across all platforms show on one page. Thanks

**Comment by almac7r** [comment]
ok, any way for me to go back to the previous version?

**Comment by magneticchen** [comment]
No. You are unable to roll back.
