### ISSUE TITLE
Scraped images gone after last update in LIST view

### ISSUE THREAD

**Issue by ghiki** [magneticchen/Daijishou#295]
After 1.4.10 update, if I go to "list view", all the games appears without picture, but after switching to "grid view", all the box-arts appears again only in this view.

List view:
![Screenshot_20230312-142022](https://user-images.githubusercontent.com/854302/224547670-88401b41-60cf-4143-9b8d-2662e6c03045.png)

Grid view:
![Screenshot_20230312-142403](https://user-images.githubusercontent.com/854302/224547674-acac33dc-9275-478f-a353-48525710e0b7.png)

All the covers are obtanined by the scraping function

**Comment by magneticchen** [comment]
Can you open the logger and check if anything suspicious?

**Comment by ghiki** [comment]
Nothing strange at all in the log, but I think the cause is due to some "new logic" implemented in Daijisho; after the last update, it shows in-game screen (major of the times the "new game" screen) instead of cover-art, but only in list view, in grid view, it shows cover art correctly. It happens to all the platforms:

I attached a quick video showing it

https://user-images.githubusercontent.com/854302/224552863-11c7336f-12d0-4ec2-b1ad-bae21396eed9.mp4

**Comment by magneticchen** [comment]
Please touch the thumbnail again. You've switch view mode.

**Comment by magneticchen** [comment]
https://youtu.be/298d9van4fg?t=21

Here is a video illustrates it. (At 21 sec)

**Comment by ghiki** [comment]
LOL! I didn't know that, thanks!

**Comment by magneticchen** [comment]
No worries
