### ISSUE TITLE
Crashes after launching Mario Kart Wii

### ISSUE THREAD

**Issue by currall** [magneticchen/Daijishou#300]
Launching any other game works fine, but I replaced my mario kart wii rom with a different one and now launching it crashes. It works fine launching through the dolphin user interface.

![Screenshot_20230313-192921](https://user-images.githubusercontent.com/29579820/224812631-5d84a8a9-8cbd-4eee-af47-ef0fab722d07.png)

**Comment by magneticchen** [comment]
Fixed in `1.4.16`. Please wait for the update.

**Comment by magneticchen** [comment]
https://github.com/magneticchen/Daijishou/releases/tag/v1.4.16
