### ISSUE TITLE
AetherSX2

### ISSUE THREAD

**Issue by almac7r** [magneticchen/Daijishou#302]
AetherSX2 now loads into AetherSX2 home screen instead of directly into the rom. Could this be due to the recent AetherSX2 update that has now introduced ads ?

**Comment by magneticchen** [comment]
![Screenshot 2023-03-14 at 17 12 23](https://user-images.githubusercontent.com/22817012/224952324-f97e61ef-0ec6-4648-90dd-3a00b3514d0d.png)
