### ISSUE TITLE
Scraping broken for Arcade after latest update

### ISSUE THREAD

**Issue by dabbler77** [magneticchen/Daijishou#304]
Despite a fresh install. Daijishou wont scrape ARCADE(FBNEO) or ARCADE(MAME) correctly since the latest update (v1.4.x). *some* cover images are downloaded.  No names are correctly scraped, only the short rom zip names are displayed.

Versions prior to the recent 1.4.x updates scraped all names and images fine! (The contents of my arcade rom folder has not changed!)

Edit: Other platforms continue to scrape fine (images and name)

**Comment by magneticchen** [comment]
Hello. Me and @Post-Mortem have tested that. And ours both work fine. Please clear cache and make sure that Aracade Italia site is up.

**Comment by josehand1** [comment]
I'm having the same issue on mine. What cache do you suggest us to clear? So I can test it as well

**Comment by dabbler77** [comment]
> 

This maybe an issue with arcadeitalia then. How can we force the scraper to use other sources?

**Comment by Howchie** [comment]
I'm seeing similar difficulties, it's currently scraping the covers but not the names of the games. Though it has for a couple of them, so perhaps there's intermittent periods where some aspects of the API aren't working?

**Comment by dabbler77** [comment]
It would appear to be a bad co-incidence with the latest Daijisho release and arcadeitalia expereincing issues. I can confirm that today, Daijisho is scraping Arcade Italia fine. This can be closed.

**Comment by dabbler77** [comment]
Even though ArcadeItalia seems to be back on line, Dasijisho is failing to scrape large amounts, if i populate the roms folder with smaller, say 20 items at a time, it does scrape. I think this maybe a restriction on ArcadeItalia to stop it being abused? Best solution would be other scraping sources.

**Comment by Howchie** [comment]
It's a local IP limit, you can test it by using a VPN which allows you to
scrape some more

**Comment by Realrowdy** [comment]
Also had to use a VPN. Still only did 10 at most per VPN. Wow it took forever to do 2133 files. And some files never matched up. And it counted those evertime it tried to scrape. Had switch VPN multiple times while scrapping. Super pain in the ass.

**Comment by Howchie** [comment]
Is there a guide I can follow for getting stuff from Skraper across to Daijisho?

**Comment by actionmissiles** [comment]
Hey, I am having the exact same issue, it was strange, it seemed to work periodically? I am getting pretty frustrated by it not correcting the titles, it makes things very obnoxious to look through... and it teased me by doing it currently up until a certain letter. I think "C" ? and then it went back to leaving them their abbreviated .zip file name. Is there a limit on how much you can do? I broke up my folders by letter, started with the # titles, which only had about 98 files in it, and it still seems to be happening. Will try clearing the cache, but I actually deleted and reinstalled Daijisho and it still seems to be happening. Any advice on this is greatly appreciated. Thanks

**Comment by tallpr24** [comment]
I’m having the same issue, even when using vpn, any suggestions, only happening with mame or fbneo

**Comment by Post-Mortem** [comment]
> Hey, I am having the exact same issue, it was strange, it seemed to work periodically? I am getting pretty frustrated by it not correcting the titles, it makes things very obnoxious to look through... and it teased me by doing it currently up until a certain letter. I think "C" ? and then it went back to leaving them their abbreviated .zip file name. Is there a limit on how much you can do? I broke up my roms by letter, started with the # titles, which only had about 98 files in it, and it still seems to be happening. Will try clearing the cache, but I actually deleted and reinstalled Daijisho and it still seems to be happening. Any advice on this is greatly appreciated. Thanks

This is not a Daijisho issue, arcade italia (the site from where daijisho scrapes arcade roms) has a limit. You can try scraping later or use a vpn or connect through a different wifi.

**Comment by Post-Mortem** [comment]
> I’m having the same issue, even when using vpn, any suggestions, only happening with mame or fbneo

Try again later or use different internet connection.

**Comment by hifihedgehog** [comment]
Still not working. I have used even multiple Outline VPN connections to try to fool Arcade Italia and I can only get through about 500-600 roms in MAMEs. The issue is Daijishou doesn't let us start scraping across a given subset of games in the platform. So Arcade Italia will as it goes through the scrape disconnect after the first few dozen games. If Daijishou could let us scrape a given selection of ROMs, that could get around Arcade Italia's nonsensical rate limiting.

**Comment by actionmissiles** [comment]
I ended up getting Launchbox, just because I'm a nit-picky son of a bitch.
I really wanted Daijisho to work, because I think I liked it better. Please
let me know if you ever manage to get it to work smoothly!

Chris

**Comment by Howchie** [comment]
Just a suggestion, given this issue only affects arcade roms which have a
fairly standardised naming scheme, is there a way daijisho can just cache
the metadata for these directly rather than doing a search per user?

**Comment by actionmissiles** [comment]
I thought about that, I thought I did see something out there that did
maybe mention it? But I'm lazy and went the easy route, please let me know
if you ever discover anything like that / are able to get it to work, if
you don't mind.

Chris

**Comment by DarkGalaxies** [comment]
What if you have the Boxart and the video content 
I can't seam to scrape the Boxart locally 
Is there a way to scrape them locally

**Comment by actionmissiles** [comment]
I think there is but I just gave up and bought a launchbox I'm afraid :( -
let me know if you manage to find a good solution please.

Chris

**Comment by DarkGalaxies** [comment]
Hey I don’t know same here trying to figure out how to do it I have launchbox too for both windows and android both pie life time HassanAm 19.12.2023 um 02:39 schrieb actionmissiles ***@***.***>:﻿
I think there is but I just gave up and bought a launchbox I'm afraid :( -

let me know if you manage to find a good solution please.



Chris





On Mon, Dec 18, 2023 at 8:22 PM DarkGalaxies ***@***.***>

wrote:
