### ISSUE TITLE
Sega CD 32X Platform

### ISSUE THREAD

**Issue by Kmog2185** [magneticchen/Daijishou#305]
Could you please add the Sega CD 32X as a system?
![Mega_Drive_II_(PAL)_+_Mega-CD_II_(PAL)_+_32X_(PAL)](https://user-images.githubusercontent.com/127875716/225066394-cfef98c4-e6ae-417c-b22c-dae1fea543b2.png)

**Comment by Kmog2185** [comment]
The combination of the two add ons, as there were games exclusive to the combination.

**Comment by magneticchen** [comment]
Isn't it there already? 

https://github.com/magneticchen/Daijishou/blob/main/platforms/Sega32X.json

**Comment by Kmog2185** [comment]
That would be just the 32X on it's own. The combination of the Sega CD and 32X to the Genesis is considered it's own system because of it's own seperate library.
