### ISSUE TITLE
I start PS2 games from Daijisho and it sends me directly to the emulator

### ISSUE THREAD

**Issue by MiguelCardonaG** [magneticchen/Daijishou#308]
When I'm going to try to start any ps2 game through Daijisho, this one sends me to the AetherSX2 emulator v1.5-4248 It is an alpha version, I do not know if it will have anything to do with it. I have started other games from other emulators and it works fine.

I have uninstalled Daijisho and reinstalled it but the problem persists, I don't remember that happening before.

Daijisho version is 1.4.18 (350).

**Comment by magneticchen** [comment]
Please checkout the latest news about AetherSX2.

https://github.com/magneticchen/Daijishou/issues/302

**Comment by MiguelCardonaG** [comment]
Oh! I've seen it. I think I'm going to close it because it's not the launcher's problem.
