### ISSUE TITLE
App does not open, error code 2067 SQLITE_CONSTRAINT_UNIQUE

### ISSUE THREAD

**Issue by NaitsirkC** [magneticchen/Daijishou#312]
Updated the app today via the app store on Retroid Pocket 3+, android 11, and started getting this error. The app will not open, simply crashes and gives the error before making it past the splash screen. I cleared the cache, same issue, updated using the latest github apk (newer than the play store version, 1.4.24), still the same error. I found a post on reddit with the exact same error: 

https://www.reddit.com/r/retroid/comments/11rjdwm/anyone_else_getting_this_error_when_launching/

![20230315_132404](https://user-images.githubusercontent.com/38174507/225413644-3f64c043-0ae2-42db-bcb6-a3f169731e88.jpg)

**Comment by magneticchen** [comment]
Hello. Could you explain more about what dose it mean it occurred randomly. (It should occur on every start up afaik.)

**Comment by magneticchen** [comment]
Hello. Please check the latest release. Thanks.

https://github.com/magneticchen/Daijishou/releases/latest

**Comment by NaitsirkC** [comment]
That seems to have done the trick! Thank you so much!

**Comment by magneticchen** [comment]
Thanks for the report. I will leave this open for a while.

**Comment by NaitsirkC** [comment]
No problem, super happy to be back on my favorite launcher :D

**Comment by Vertigo-Git** [comment]
> Hello. Could you explain more about what does it mean it occurred randomly. (It should occur on every start up afaik.)

Sorry I should have been more clear. I get the error every time I launch it, it just "randomly" started and never stopped.

**Comment by Vertigo-Git** [comment]
I just downloaded the latest release and it worked! Thanks for the fix!
