### ISSUE TITLE
Arcades not updating the title anymore when scraping

### ISSUE THREAD

**Issue by cvg095** [magneticchen/Daijishou#313]
Good day just reinstalled daijisho because it wont open anymore after updating to the latest version. Had to resync all again, just realized that titles of naomi,neogeo and mame are not updating anymore. Please fix thank you
![P_20230316_074713](https://user-images.githubusercontent.com/114903208/225469165-e2f63aba-8d74-4de8-886d-11b91a5c92fc.jpg)

**Comment by magneticchen** [comment]
#304

**Comment by cvg095** [comment]
Thank you
