### ISSUE TITLE
SCUMMVM TAB

### ISSUE THREAD

**Issue by adamthepyramid** [magneticchen/Daijishou#32]
Hello
Is it possible to get SCUMMVM as a platform and a player ? I would like to add it to the app

**Comment by magneticchen** [comment]
Hey, I have added to the platforms list!

**Comment by adamthepyramid** [comment]
Retroarch doesn't have scummvm how can I change it so it loads an independent emulator

And again thank you

**Comment by magneticchen** [comment]
Hey I've seen that scummvm on the retroarch.
![IMG_20220603_032813_210](https://user-images.githubusercontent.com/22817012/171722660-caa776d3-db95-450f-88cc-cc15563ee862.jpg)

However, I will still check out standalone when available.

**Comment by magneticchen** [comment]
Didn't find a way to do so. Will close it for now.
