### ISSUE TITLE
[bugs report] Launching PSP and PS2 games

### ISSUE THREAD

**Issue by Tempaccnt** [magneticchen/Daijishou#322]
I will make it short

when Launching PSP game, the game resolution becomes messed up untill the game is restarted from inside ppsspp or you change the backend setting in ppsspp.

when Launching a PS2 game, instead of launching the game, the app opens AetherSX2 and you need to select the game again before it launches.

My Device:
Phone-Huawei P30 Pro
RAM-8GB
chip-Kirin980
GPU-Mali-G76
PPSSPP Version-1.14.4
AetherSX2 Version-V1.4-3064

**Comment by MiguelCardonaG** [comment]
Aethersx2:

https://github.com/magneticchen/Daijishou/issues/308

**Comment by Tempaccnt** [comment]
> Aethersx2:
> 
> #308

I see. that take care of the second issue. Thanks

**Comment by magneticchen** [comment]
For the first one.
#179
