### ISSUE TITLE
Add action to hide all titles without box art

### ISSUE THREAD

**Issue by DieHardMan5x** [magneticchen/Daijishou#326]
![Screenshot_20230319-152116](https://user-images.githubusercontent.com/74651322/226182635-06bd0e23-1d88-4214-97e7-a3961e8bcbc6.png)

This is a feature request. Can you please add an action to hide all titles (visibility) without a box art?

**Comment by magneticchen** [comment]
Sorry but this is not planned. Library logic should be attached to whether media exists or not.

**Comment by DieHardMan5x** [comment]
Ok, I understand that, what I meant is a way to hide all titles on a platform that don't have a box cover.

![Screenshot_20230325-174837](https://user-images.githubusercontent.com/74651322/227731407-6fc592f2-3c9f-4378-8d72-1ea13a3ebe30.png)
![Screenshot_20230325-174821](https://user-images.githubusercontent.com/74651322/227731408-a4c2b135-be5d-4c23-8e68-66740db48ae0.png)

**Comment by magneticchen** [comment]
Sorry. But library logic should not be coupled to whether media exists or not.
