### ISSUE TITLE
Scraper scrapes the wrong genre

### ISSUE THREAD

**Issue by NobleStripes** [magneticchen/Daijishou#329]
![image](https://user-images.githubusercontent.com/78245047/226750899-a7e63b6c-f3cd-447a-8b31-2bf3788cade3.jpg)
DSESS scraper suddenly gives my games the wrong genre, I have Resident Evil suddenly becoming RPG whereas it should be horror and shooter. Plus there are many games getting genres that were never meant for them.

**Comment by magneticchen** [comment]
The genre editor for item is available in the latest version.
