### ISSUE TITLE
Add support for John NESS

### ISSUE THREAD

**Issue by MiguelCardonaG** [magneticchen/Daijishou#335]
Could John NESS be added to the list of compatible emulators?

https://play.google.com/store/apps/details?id=com.johnemulators.johnness

**Comment by Jetup13** [comment]
Doesn't seem like it supports launching from front-ends. I got starting permission denial errors when trying it. Pegasus, another android front-end, [shows that it has no support](https://pegasus-frontend.org/docs/user-guide/platform-android/)

**Comment by MiguelCardonaG** [comment]
> Doesn't seem like it supports launching from front-ends. I got starting permission denial errors when trying it. Pegasus, another android front-end, [shows that it has no support](https://pegasus-frontend.org/docs/user-guide/platform-android/)

Well, go wrong, AetherSX2 is not compatible either.
