### ISSUE TITLE
Sega Pico

### ISSUE THREAD

**Issue by Kmog2185** [magneticchen/Daijishou#341]
Could you add the Sega Pico as it's own system since it is the only Sega system to not be on this frontend?

**Comment by Kmog2185** [comment]
Also, could you add the Advanced Pico Beena as a platform as well?

**Comment by Jetup13** [comment]
Updated and added Sega Pico

Not sure what Advanced Pico Beena is and if an android core/emulator can play it. I've only tested Sega Pico on the picodrive core
