### ISSUE TITLE
No "+New Widget" button on the widgets page

### ISSUE THREAD

**Issue by voidbrain** [magneticchen/Daijishou#342]
Widgets page is blank and there is no way to add widgets.

Retroid Pocket 3+
v 1.0.0.86
Dajishou 1.4.30 (362)

**Comment by magneticchen** [comment]
Please disable kiosk mode.

**Comment by voidbrain** [comment]
Thanks. 
But on Android "Kiosk" is a lock down mechanism that enables to run a single app.
Maybe it's not just me that's confusing
