### ISSUE TITLE
Touchscreen bug after changing the navigation gesture type

### ISSUE THREAD

**Issue by sunydo** [magneticchen/Daijishou#346]
After updating to the latest version, there is a major issue where the touchscreen occasionally becomes unresponsive. The only way to solve this problem is to restart the device, but the issue may reoccur repeatedly.

**Comment by magneticchen** [comment]
Sorry. Does it occurred only in Dai or outside of the app. Also can you explain more about how is it being unresponsive. How do I reproduce the unresponsiveness. Thanks.

**Comment by sunydo** [comment]
When I switch Android gesture types, this bug appears, and this issue only occurs on the Daijishou front end. Switching to the Android interface restores normal touchscreen functionality

**Comment by magneticchen** [comment]
May I ask which Android version you are using?

**Comment by sunydo** [comment]
The current version being used is Android 11，Every time I switch between these two, a bug appears, and it only affects touchscreen functionality on the Daijishou front end
![1](https://user-images.githubusercontent.com/63689398/227776751-8af57966-4fff-4947-b1ec-e8905c654633.png)

**Comment by magneticchen** [comment]
Thanks for the response. I will check this issue.

**Comment by magneticchen** [comment]
This is an Android 11 bug. The fixes will be patched. In `1.4.37`.
