### ISSUE TITLE
Import Preview Media Feature cant import Game Title and Game Metadata

### ISSUE THREAD

**Issue by otddev** [magneticchen/Daijishou#349]
I have been utilizing skraper to get the data missing on the games I have added, the default scraping system has it limited especially for users with large collections. Using the import preview media was awesome but lacks the capacity to fully utilize the data collected by SKRAPER. 

Current: (The following can be imported.)
- Box Art Images
- Screenshot Images
- Title Image

Not Available: (The data within SKRAPER that Daijishou does not utilize.)
- Game Title > This can be imported from the *.dat file generated per system by the SKRAPER tool. By default, the file is generated on the exact locations as the roms.
- Game Description > This can also be located from the same *.dat file.
- Game Metadata (ex. Category / Genre / etc) > This can be located from the same *.dat file.

Think adding the capacity to import this other data will solve many problems specially the current limit issue with the default scraper used by Daijishou.

**Comment by jaildesigner** [comment]
Please add this. Arcade Italia is no longer a valid scraper source

**Comment by magneticchen** [comment]
Will be added in `1.4.41`.

**Comment by magneticchen** [comment]
But I don't see genres in the `.dat` file.

**Comment by josehand1** [comment]
![image](https://user-images.githubusercontent.com/66196742/228255184-4ff17b51-083e-40ad-b199-812684ba7158.png)

It exists on my .xml files from Skraper

**Comment by magneticchen** [comment]
Can you teach me how to enable that. Thanks.

**Comment by josehand1** [comment]
![image](https://user-images.githubusercontent.com/66196742/228257458-f4c059ef-e648-4e82-b745-a76c2aad255e.png)

It's on the third checkbox and it's always enabled, under Name and Description. I believe after every scraping from Skraper it should bring Genre together with the other info. Do you have an example of how your .xml file looks?

**Comment by magneticchen** [comment]
Hmmm I not have that. Here is the sample of mine.
```

  <game name="Elite Soccer">
    <description>Elite Soccer lets the player choose from 24 National teams including the U.S., England, France, Brazil among others, in a chance to play in the World Cup tournament and win the coveted trophy. Players can also choose to play in a Knockout-style tournament where instead of a round robin type of play like in World Cup, they instead play one game and advance to the next like a regular tournament. There is also a two-player mode that allows friends to compete head-to-head.&#xD;
&#xD;
The main gameplay is the same as others with an overhead view with a third-person perspective for penalty kicks. The rules and regulations are up to date and can actually be changed to suit the players style of choice. They can also choose weather conditions, skills of goalies or even the choice to play either indoors or outdoors. Players can also edit their players including appearance and stats wise to suit their liking.</description>
    <year>1994</year>
    <manufacturer>GameTek</manufacturer>
    <rom name="Elite Soccer (USA) (SGB Enhanced).gb" size="131072" />
  </game>
  <game name="We're Back! : A Dinosaur's Story">
    <description>We're Back! is an Action game, developed by Beam Software and published by Hi Tech Expressions, which was released in 1993.</description>
    <year>1993</year>
    <manufacturer>Laser Beam Entertainment</manufacturer>
    <rom name="We're Back! - A Dinosaur's Story (USA, Europe).gb" size="131072" />
  </game>
  <game name="Mickey's Chase">
    <description>In Mickey's Dangerous Chase the player takes control of either Mickey or Minnie Mouse.  While on his way to deliver a very special gift to his girlfriend Minnie, Mickey is jumped by Pete who steals the present and takes off and it is up to the mouse duo to stop Pete and get back the present.

The gameplay is a side-scroller, where players pick up boxes to throw at enemies as well as discover power-ups that include short bursts of invincibility, extra lives and energy boosts that will help the player in their quest.  There are five different levels to play in including a lake, a mountain top, a forest and a shopping center and numerous enemies to avoid such as spiders, flying squirrels and even snowballs.</description>
    <year>1992</year>
    <manufacturer>Capcom</manufacturer>
    <rom name="Mickey's Dangerous Chase (USA).gb" size="131072" />
  </game>
```

**Comment by josehand1** [comment]
![image](https://user-images.githubusercontent.com/66196742/228260265-7bd5499a-bd15-464d-95eb-569b03b873f1.png)

What frontend do you have set up here? The "correct" one is Recalbox, which brings the most detailed results and that can be converted to other standards like Pegasus,

**Comment by jaildesigner** [comment]
You can pick generic or recalbox. It doesn’t matter. You have to specify which xml format you want. Let me take a pic

**Comment by magneticchen** [comment]
Ok cool thank you.

**Comment by jaildesigner** [comment]
Game List -> Emulationstation. Gamelist.xml

**Comment by magneticchen** [comment]
Another report: `.xml` with genres is added as well.
