### ISSUE TITLE
Sync doesn't remove games that no longer exist

### ISSUE THREAD

**Issue by dirn** [magneticchen/Daijishou#35]
I renamed some of my Dreamcast chd files and ran a sync. I now have duplicate entries. Attempting to play the game recognizes that the file no longer exists, but there doesn't seem to be a way to remove it from the library.

**Comment by magneticchen** [comment]
Hello, thanks for reporting. You can try to delete the platform then download it again.

**Comment by dirn** [comment]
Thanks for the suggestion. That definitely works as an interim solution.

**Comment by magneticchen** [comment]
In upcoming version 1.2.25 will add an action "clear_all_disjointed_playable_items" to resolve the issue.
