### ISSUE TITLE
Request: Close Emulators Gracefully With SIGTERM, Rather Than killBackgroundProcesses

### ISSUE THREAD

**Issue by isosphere** [magneticchen/Daijishou#351]
I'm not sure if this is allowed in the Android permission system without root access, so maybe what I'm asking for is functionally impossible

Daijishou kills emulators when starting a different ROM, I suspect it does this using `killBackgroundProcess`.

Unfortunately the immediacy of that command prevents emulators from doing any "on close" behaviour. For example, RetroArch can be configured to save state on close, I think it also saves changed config on close. This only happens on graceful closes, the kill signal prevents that from happening.

I have a limited understanding of the Android API; I couldn't find an API-way of gracefully terminating other processes.

However, we might be able to manually call the `kill` command line utility and specify `-SIGTERM` (rather than `-SIGKILL`) with the appropriate PID. 

It's certainly more complicated to implement and would require finding the PID first, but it would allow Daijishou to gracefully terminate other processes and allow them to do some cleanup work before they close.

**Comment by isosphere** [comment]
I would label this as requested in #254, but I don't seem to have the requisite permissions to do so.

**Comment by isosphere** [comment]
Poop. Thanks for the response!

**Comment by magneticchen** [comment]
Actually some standalone like mupen64 handle resume/transition pretty well.
