### ISSUE TITLE
Return scan ROM files for each platform

### ISSUE THREAD

**Issue by pantey** [magneticchen/Daijishou#363]
In version 1.4 it is no longer possible to sync a new ROM file for the platform, the only option is to start syncing the entire library. 512GB memory card (36 platforms), synchronizes approximately 6 hours. It's horrible.

**Comment by Jetup13** [comment]
> Highlight Platform > Path > Sync

**Comment by pantey** [comment]
> > Highlight Platform > Path > Sync

Thank you, this is the last place I would look.
