### ISSUE TITLE
Import EmulationStation XML and Images

### ISSUE THREAD

**Issue by davidonabus** [magneticchen/Daijishou#365]
I've read that using XML files is now supported. How does it work? I've tried two things:
1) I added a new system, added the path, and synced. I then edited it the platform and then selected "Import .XML File" and navigated to my folder with roms and media. I selected the XML file and it said "Added Successfully" but no images were updated for my added roms.

2) I added a new system but didn't add a roms path or sync. I then edited the platform and selected "Import .XML File" and navigated to my folder with roms and media. I selected the XML file and it said "Added Successfully" but no roms or images were added to the platform.

Thank you

**Comment by chronox777** [comment]
the way i did :
1. add platform
2. add path and finish
3. edit platform, unmark scrape preview media, import preview media (for each titleshot, screenshot and boxart in different folders and the name for each image is the same as rom name). 
4. import xml file (i use gamelist.xml generated by arrm scrapper).
5. import dat file

i don't know if it is the correct procedure, but only by following these i can have all the info for the games displayed by daijisho.

**Comment by magneticchen** [comment]
@davidonabus @chronox777 gave a pretty complete answer for it.
