### ISSUE TITLE
Video Preview in Detail Screen - Suggestion

### ISSUE THREAD

**Issue by davidonabus** [magneticchen/Daijishou#369]
I love the autoplay of the video for each rom in the Details screen. Would it be possible to add the ability to remove the black scrim/overlay and see the video without the rest of the screen details? This would be better than clicking the "video" button which currently takes you to the youtube interface (forcing you to start the video from scratch).

**Comment by magneticchen** [comment]
Sorry it is not possible. Youtube component that Dai is using doesn't support that.
