### ISSUE TITLE
Android as a platform

### ISSUE THREAD

**Issue by LegendDarkness97** [magneticchen/Daijishou#37]
Hi,
would it be possible to add Android as a platform (for native Android games) - similiar to how Dig does it? Adding Games (or other apps) to that platform could be done via an additional context action in the 'Apps' tab. 
While you can start native Android games via the 'Apps' tab, at least personally, I prefer not to hide all non-game apps. In addition, having an Android platform would make switching between retro games and native Android games feel more coherent and seemless. Still, the logic for this platform would need to be quite different to all other ones so I dont know how difficult it would be to implement.

Regardless, great work on Daijisho, it is propably my favourite retro frontend on Android at the moment.

**Comment by magneticchen** [comment]
Thanks for bringing it up. Will leave it open until solutions come up.

**Comment by rockedsocks** [comment]
I think adding android games as a separate tab in the launcher might help. Either that or making widgets launch apps/ adding dividers could help

**Comment by magneticchen** [comment]
After trying implantation for Android apps as a platform. Thumbs looks like crap, result is not fluid. And the FLAG_IS_GAME often includes emulators apps.
 So I eventually add a "only games" options along with show/hide game button in apps page. On version 1.2.12. 
And with the version. If ppl really want that Android platform you can manually download and manually import Android platform from this GitHub page.

**Comment by magneticchen** [comment]
https://github.com/magneticchen/Daijishou/blob/main/platforms/Android.json.deprecated

**Comment by pomdtr** [comment]
It would be cool to be able to mark an app as a game. The Xbox apps do not show up with the only games filter.

**Comment by LegendDarkness97** [comment]
Same issue with KOTOR. Strangely in DIG it does, but that has some massive issues with other platforms. On the other hand, being able to hide apps in the "only games" filter would be nice as well, because, as you said, the emulators show up as well.
Would marking an app as a game result in it appearing in the Android platform as well? Because that would be nice, but I also understand that the Android platform was more of a test and thus not a focus of further development.

**Comment by pomdtr** [comment]
I think having a favourite filter in the app screen would solve my issue. It would be able to favourite all of my games, without depending on some kind of tags set by the apps devs.

**Comment by LegendDarkness97** [comment]
Yeah, that would work as well. Coupling the Android platform with the favorites selection would then be nice as well (if it isnt too much work). Because I actually like it. Yes, the thumbnails arent great, but at least on my Retroid Pocket 2+ it feels like using any other platform. My only issue currently with it is, as already mentioned, that some games (AM2R and SW KOTOR for me) are missing and I cant manually add them. Otherwise it works fine.

**Comment by magneticchen** [comment]
> I think having a favourite filter in the app screen would solve my issue. It would allow me to favourite all of my games, without depending on some kind of tags set by the apps devs.

Instead of favourite apps. Daijihou provides "hiding apps" ability. Doesn't know if that will help tho.

**Comment by magneticchen** [comment]
Will replace current hidden mode by introducing flag/unflag apps in future 1.3.x version. (Two mode "all apps" and "games")

**Comment by magneticchen** [comment]
The changes have made in 1.3

**Comment by magneticchen** [comment]
![IMG_20220817_045942_388](https://user-images.githubusercontent.com/22817012/184984177-2735fbc1-01e6-4a26-ba26-be49b665439e.jpg)
![IMG_20220817_050036_835](https://user-images.githubusercontent.com/22817012/184984296-b9fb32da-e036-4b3b-8a97-62160dd16adf.jpg)
