### ISSUE TITLE
Import XML - Description not imported

### ISSUE THREAD

**Issue by davidonabus** [magneticchen/Daijishou#370]
Importing my XML doesn't result in either of the following being imported:
<name>
<desc>

Is this a bug, or has this functionality not yet been implemented?

**Comment by magneticchen** [comment]
Make sure that your XML is emulationstation format.

**Comment by davidonabus** [comment]
I'm using skraper, and I'm select recalbox as my format.

![image](https://user-images.githubusercontent.com/6895542/230655084-88cdfb22-9f85-49cd-a19a-bc3318cbf6aa.png)

**Comment by magneticchen** [comment]
Hello. There is a bug for XML importing. Will be fixed next version (`1.4.47`).
