### ISSUE TITLE
"new" tag not disappearing after launching a "new" game

### ISSUE THREAD

**Issue by Cinystre** [magneticchen/Daijishou#374]
Hey, just a small issue concerning the new tag on all games I've added to the library, version 1.4.48 on Retroid Pocket 3+. Some people on the Retro Handhelds discord also have this issue (unknown versions, but I've tested 1.4.0 and it's the same). No matter what I try the new tag stay even though I've launched 10 times a game. Tried removing the whole library and resyncing, no change. 

Thank you for your work, have a nice day !

**Comment by Post-Mortem** [comment]
Hey, the new game tag goes away after 3 days.
