### ISSUE TITLE
Show all 5 top buttons instead of scrolling

### ISSUE THREAD

**Issue by MonkoftheFunk** [magneticchen/Daijishou#4]
There is enough room to show them all, why hide apps and settings. Making settings button more available allows it to be used as a back button when inspecting players or platforms and other setting screens.

![Screenshot_20220311-083307~2](https://user-images.githubusercontent.com/639841/157908803-47ff119a-c951-408a-a374-6de151851d81.png)

**Comment by magneticchen** [comment]
Have updated and will be included in the next updates.
