### ISSUE TITLE
Key combo to set screen brightness

### ISSUE THREAD

**Issue by sargant** [magneticchen/Daijishou#41]
When using the app on a gaming handheld such as the Odin, it blocks the ability to use the gesture bar and pull down to access quick settings.

Would it be possible to have a key combo to set brightness without navigating manually to settings?

**Comment by magneticchen** [comment]
I don't know about Odin. But on my RP2+ pull down to access quick settings is possible as well as the others device too! Is it something specifically to Odin OS thing?

**Comment by magneticchen** [comment]
> Would it be possible to have a key combo to set brightness without navigating manually to settings?
I think is No. Since that is out of scope of what Daijishou should handle.

**Comment by sargant** [comment]
> I don't know about Odin. But on my RP2+ pull down to access quick settings is possible as well as the others device too! Is it something specifically to Odin OS thing?

It is possible, but extremely difficult and takes multiple tries. Might be something to do with full-screen App behaviour  m

**Comment by magneticchen** [comment]
Thanks for bring this up. But is not planned currently.
