### ISSUE TITLE
Select chars in file name break scraper

### ISSUE THREAD

**Issue by dabbler77** [magneticchen/Daijishou#43]
% is considered an illegal char when scraping. For example, TG16 - "Asuka 120% Maxima Burning Fest" wont scrape and displays error "illegal char", if i rename the file to ""Asuka 120 Maxima Burning Fest", the scraper dosnt error, but then dosnt find the title!

Can % and other common chars be allowed and not considered illegal to fix this?

**Comment by magneticchen** [comment]
Thanks for reporting. Will check it when available.

**Comment by magneticchen** [comment]
I've tested it. The summary of this title is just not found on Google. Thus so do daijishou.
