### ISSUE TITLE
GBA platform not loading retroarch

### ISSUE THREAD

**Issue by RedZombieHD** [magneticchen/Daijishou#44]
When using Retroarch 32bit on the gba platform, I get the error "Player error: Unable to find explicit activity class {com.retroarch.ra32/com.retroarch.ra32.browser.retroactivity.RetroActivityFuture};

I'm using the correct index.json and I've checked the GBA.json file and the only thing that might be wrong is the `com.retroarch` is missing in ` "amStartArguments": "-n com.retroarch.ra32/.browser.retroactivity.RetroActivityFuture\n` when in other platforms its `"amStartArguments": "-n com.retroarch.ra32/com.retroarch.browser.retroactivity.RetroActivityFuture\n`

**Comment by magneticchen** [comment]
Thanks mate. Hadn't noticed that previously. Have fixed, redownload and replace should works!
