### ISSUE TITLE
Add MMJR2 Lumince fork

### ISSUE THREAD

**Issue by German-Herrador** [magneticchen/Daijishou#45]
Add Lumince version of the MMJR2 fork to the available players.

**Comment by magneticchen** [comment]
I can't install the app on my rp2+ to test it. But I found it has the same package name as the "Dolphin mmjr" one. You can test that version to see if is working for you.

**Comment by German-Herrador** [comment]
> I can't install the app on my rp2+ to test it. But I found it has the same package name as the "Dolphin mmjr" one. You can test that version to see if is working for you.



> I can't install the app on my rp2+ to test it. But I found it has the same package name as the "Dolphin mmjr" one. You can test that version to see if is working for you.

You're right. If you select "Dolphin.org.mm.jr fork" it will launch MMJR fork and if you use "Dolphin mmjr" it will launch MMJR2 fork. I don't know if the name can be changed or if it'll be better to leave it that way. If you think that solves the problem you can close this issue.

**Comment by magneticchen** [comment]
Thank you
