### ISSUE TITLE
Retroarch 64 freezes on launch

### ISSUE THREAD

**Issue by movinonup** [magneticchen/Daijishou#479]
Opening the same game in Retroarch directly works fine.  However, when I try to launch the game from Daijisho with the (same, correct core selected), Retroarch freezes on launch.  On a Logitech G Cloud.

**Comment by TapiocaFox** [comment]
Could you provide more details. Like screenshots perhaps?

**Comment by uncannyken** [comment]
I discovered the issue happened only when my ROMs were on an SD card.  Once I moved them to internal device storage, Retroarch launched games fine from Daijisho.

**Comment by movinonup** [comment]
I discovered the issue happened only when my ROMs were on an SD card. Once I moved them to internal device storage, Daijisho launched games fine using Retroarch.
