### ISSUE TITLE
Not loading paths

### ISSUE THREAD

**Issue by HoovyRoovy** [magneticchen/Daijishou#48]
I don't know if it has something to do with my device specifically (it might) but whenever I load a path, it will not show up, I tried uninstalling and reinstalling and it just won't work. I am very stressed about it; can somebody help me to try and find what I'm doing wrong?

**Comment by HoovyRoovy** [comment]
https://streamable.com/jwri1b

**Comment by magneticchen** [comment]
Thanks for reporting. For convenient I will discuss the issue with you on discord!

**Comment by magneticchen** [comment]
Np mate.
