### ISSUE TITLE
Option to use gamesdb scraping

### ISSUE THREAD

**Issue by MonkoftheFunk** [magneticchen/Daijishou#5]
They have api as well
https://api.thegamesdb.net/
https://thegamesdb.net/
I see you load details from wikipedia on first request, perhaps a setting to also sync details so that maybe (should be another issue) able to filter by genre/player count.... (Gamesdb has those values)

**Comment by magneticchen** [comment]
Thanks. After some investigations. I will try to implement the IGDB api from twitch first.

**Comment by magneticchen** [comment]
New source for MAME "ARCADE_ITALIA:MAME" will be available started with version 101(1.1.75)
