### ISSUE TITLE
Option to merge game discs/sets

### ISSUE THREAD

**Issue by Post-Mortem** [magneticchen/Daijishou#50]
If a set of files belongs to the same game, such as regional variants of a game or multi-disc games, they will be treated as a single game in lists and counts in “merged games sets” mode. 

Files are considered part of the same game if they are assigned exactly the same title, either automatically by Daijishou or manually by rematching and/or editing the titles. 

Then, when starting said game, Daijishou should provide a list of all merged sets/discs of the game.

**Comment by magneticchen** [comment]
Thanks. This is a know request. However, currently I haven't found a good way to fulfill the request. Will leave it opened until having a conclusion or taken an action.

**Comment by Post-Mortem** [comment]
Yeah, but not all emulators are compatible with m3u files, REDREAM is one of them.

**Comment by ferrazpedro** [comment]
Hey! To start, thanks @magneticchen for this awesome project! Well, right now is my favorite frontend by far, but the only thing keeping it from being perfect is the option to merge games. I do understand that games with multiple CDs can be merged in a lot of emulators by using m3u, but in my case, I use the name of the original game for all my hacked and translated games, only adding the rom name between parenthesis. So I get some situations like this:
![image](https://user-images.githubusercontent.com/37643357/188139666-b5aed188-3c2f-4351-bf95-6eeed5da8058.png)
It would be really, really great to have a option to merge these games even if only for the title. It could be a optional thing, but I think it would make life a lot easier to some people (myself included hahahaha)

**Comment by magneticchen** [comment]
Thanks for the feedback! Merge games/disk is planed as 1.4. It is planed to the next year (2023).
Sorry for the delay :D.

**Comment by magneticchen** [comment]
Have implemented in 1.4.x.

**Comment by Post-Mortem** [comment]
> Have implemented in 1.4.x.

Sexy.

**Comment by JazzJohannes** [comment]
This merge feature has been removed in the latest version. Multi-Disc games are separated e.g. in Commodore Amiga.
