### ISSUE TITLE
Feature request - Support for video backgrounds in themes

### ISSUE THREAD

**Issue by t0mg** [magneticchen/Daijishou#52]
Hi there,

Thanks for making this project, I'm rather new to Android emulation and find this to be the best implementation of a launcher. Snappy, powerful with lots of features yet straightforward to setup and use.

I have a feature request that would make it even better to me: supporting looping video backgrounds as platform themes, in order to get beautiful animations such as these: https://youtu.be/TASSFcTNslE (which I would definitely add to the theme repository as soon as it's supported).

Cheers !

**Comment by magneticchen** [comment]
Thanks that's actually a good idea. I will think about it.

**Comment by magneticchen** [comment]
The request is conflicts with the planned `1.5 The Plugin Update` (start work on it Q3. See discord discussions.)
