### ISSUE TITLE
Switching hotkey not working as intended

### ISSUE THREAD

**Issue by yotengodormir** [magneticchen/Daijishou#53]
Issue with switching hotkey. Pressing the hotkey "previous" button while on the game view will instead toggle between list and grid view. 
The hotkey works correctly while viewing platforms.

**Comment by magneticchen** [comment]
It was intentionally designed as it was. And it is not a bug. More hotkeys is the feature was supposed to introduce in 1.4. But I made it happens in 1.3 anyway. Have been included in the beta17 version.
