### ISSUE TITLE
Launching through yabasanshiro pro

### ISSUE THREAD

**Issue by LeBiquet** [magneticchen/Daijishou#54]
Hi,

First of all, thanks for your amazing work. Amazing app!

I have a small problem: launching games through yabasanshiro app does not work. It goes right back to the launcher after trying to launch the app.

Is that a known issue?

**Comment by magneticchen** [comment]
Seems like it is a known issue. People have discussed the problem on discord. Me personally have not using the yabasanshiro pro. Since my device is not capable for it so I didn't pay for it.

**Comment by LeBiquet** [comment]
Oh ok. Shit happens. I'm having trouble making beetle Saturn core to work properly. That's why I paid for yaba 2.

Thanks for the great job anyways!!

**Comment by magneticchen** [comment]
Thanks.
