### ISSUE TITLE
confirm game platform before adding entry to list

### ISSUE THREAD

**Issue by chinarut** [magneticchen/Daijishou#55]
I am indexing a small number of games  **across multiple platforms** in a single folder.
I notice when I sync, the launcher assumes all the files in the folder belong to a single platform.
It would be great if Daijishou could ID the platform of each game much like RetroArch does.
I realize using sub-folders is a workaround for now!

**Comment by magneticchen** [comment]
Hello. Each platform for a single folder is prerequisite for Daijishou. It is also a standard method like in EmulationStation. Because of the diverse range of systems often come with overlapping formats. To organize it as a whole will increasing complexities dramatically.

**Comment by chinarut** [comment]
ok - sounds like I have some reorganizing to do :-)
No worries if this just stays on a rainy day list - the workaround is acceptable ✌🏼

**Comment by magneticchen** [comment]
Thanks for the understanding. (´∀`)

**Comment by chinarut** [comment]
cleaning up GitHub.

just wanted to let you know I've been slam dunked into Batocera & tinkeromh w ES for over a year.

I am very much in the sub folder convention now & all is good in the hood 👾
