### ISSUE TITLE
Add GBA/CStand-alone Emulators

### ISSUE THREAD

**Issue by joepistachio** [magneticchen/Daijishou#57]
Please add support for My Boy! (GBA) and My OldBoy! (GB/GBC) stand-alone emulators. These allow link cable play for the Pokémon games.

**Comment by magneticchen** [comment]
Hello My Boy! series are supported they are start with com.fastemulator

**Comment by wyeley** [comment]
<div class="file-box blob-wrapper my-1" style="box-sizing: border-box; margin-top: 4px !important; margin-bottom: 4px !important; overflow: auto hidden; border: 1px solid var(--color-border-default); border-radius: 6px; color: rgb(36, 41, 47); font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-size: 14px; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;">

sources": ["https://github.com/Jetup13/es-theme-sagabox", "https://github.com/KALEL1981/es-theme-nes-box"],
--
6 | "previewThumbnailFilename": "mario.png",
7 |  
8 | "hasDefaultWallpaper": false,
9 | "defaultWallpaperFilename": null,
… |  
105 | "filename": "gbc.png"
106 | },
107 | {
108 | "matchPlatformShortname": "gc",
109 | "filename": "mario.png"
110 | },
111 | {
112 | "matchPlatformShortname": "intellivision",

</div><div class="d-flex flex-wrap text-small color-fg-muted" style="box-sizing: border-box; color: var(--color-fg-muted)  !important; flex-wrap: wrap !important; font-size: 12px !important; display: flex !important; font-family: -apple-system, BlinkMacSystemFont, &quot;Segoe UI&quot;, Helvetica, Arial, sans-serif, &quot;Apple Color Emoji&quot;, &quot;Segoe UI Emoji&quot;; font-style: normal; font-variant-ligatures: normal; font-variant-caps: normal; font-weight: 400; letter-spacing: normal; orphans: 2; text-align: start; text-indent: 0px; text-transform: none; white-space: normal; widows: 2; word-spacing: 0px; -webkit-text-stroke-width: 0px; background-color: rgb(255, 255, 255); text-decoration-thickness: initial; text-decoration-style: initial; text-decoration-color: initial;"><div class="mr-3" style="box-sizing: border-box; margin-right: 16px !important;"><span class="" style="box-sizing: border-box;"><span class="repo-language-color" style="box-sizing: border-box; position: relative; top: 1px; display: inline-block; width: 12px; height: 12px; border: 1px solid var(--color-primer-border-contrast); border-radius: 50%; background-color: rgb(41, 41, 41);"></span><span> </span><span itemprop="programmingLanguage" style="box-sizing: border-box;">JSON</span></span></div><span class="match-count mr-3" style="box-sizing: border-box; margin: 0px; font-weight: 400;">Showing the top two matches</span></div>
