### ISSUE TITLE
Any way to remove artwork corner radius?

### ISSUE THREAD

**Issue by Onkeyuk** [magneticchen/Daijishou#58]
I’m not a fan or the curved corners of the artwork. Is there a way to remove that? Or in the future an option to turn that off? Thanks!

**Comment by magneticchen** [comment]
Sorry but it is hard-coded.

**Comment by Onkeyuk** [comment]
> Sorry but it is hard-coded.

That’s a shame. Features if this frontend look amazing but wish I could change the look a little. Would prefer a different font and quote corners really but can’t be picky on a great system for free really!

**Comment by magneticchen** [comment]
It is possible but dynamically changing can be sometime expensive. And have to manage Dai to run on different specs/screen size etc. As for font I originally wanted to support but the multilingual can be a headache. Thanks for the feedback anyway. Definitely gonna keep your opinion in mind!

**Comment by Onkeyuk** [comment]
Thanks!
