### ISSUE TITLE
.emu emulators are not able to boot roms

### ISSUE THREAD

**Issue by Patchworkpupp** [magneticchen/Daijishou#59]
Any system that uses the  .emu emulators are not able to boot ROMs and just go to the main menu

**Comment by magneticchen** [comment]
Please make sure to use the latest versions of .EMU from playstore. They have updated for android SAF.

**Comment by Patchworkpupp** [comment]
I updated all versions but only snesex+ seems to work

**Comment by magneticchen** [comment]
If the SAF is not working for you. You can edit the player's `{file.uri}` to `{file.path}`. And try if it works for you.
Edit the platform, click the player to edit.

![image](https://user-images.githubusercontent.com/22817012/188484654-1a45a1f6-dc80-4afc-aca0-d613604cd8b7.png)
![image](https://user-images.githubusercontent.com/22817012/188484674-d100b979-baf4-4f21-9bb8-5383a9491a4b.png)

**Comment by Patchworkpupp** [comment]
How do I do that

**Comment by Patchworkpupp** [comment]
Ok I figured it out thanks

**Comment by magneticchen** [comment]
Thanks.
