### ISSUE TITLE
Themes 

### ISSUE THREAD

**Issue by Retro-Devils** [magneticchen/Daijishou#6]
I see you have theme colors .

I think you can make this a whole themed idea so to speak .

Heres my idea 
If every platform had a default theme, then user can change as whole theme . 
Themes would be color you have , platform wallpaper packs, and background color if possible . 

I don't know how hard this would be, but seems doable .

**Comment by Retro-Devils** [comment]
So thinking more i see a user can call platform whatever . Thats awesome.
But difficult for themes. Maybe have the default only for the ones on the github?  
Or have a "theme identifier" drop down menu in platform ?

**Comment by Retro-Devils** [comment]
Came back to say if you choice to pursue this I will gladly make default images for the systems. 
Making sure to use non copyrighted stuff.

I really enjoy the progress overall thus far and wanna see more people use it and it grow .

**Comment by Retro-Devils** [comment]
![nes-example1](https://user-images.githubusercontent.com/88673522/163513809-2b27f180-5da8-40ef-af0e-450158d03d05.png)

**Comment by Retro-Devils** [comment]
![Uploading 20220415_121143_0000.png…]()

**Comment by Retro-Devils** [comment]
![20220415_121143_0000](https://user-images.githubusercontent.com/88673522/163594599-526dd252-452b-4aa5-a5d6-c83f58598e34.png)

**Comment by magneticchen** [comment]
Thanks for your artworks. I am still thinking about how to make types of wallpapers fit on all screen sizes. For example symbolic or languages on wallpapers might not work well on all aspect ratios. But those wallpapers will flatten colors/objects work will generally. Like below.

![Screenshot_20220416-171629](https://user-images.githubusercontent.com/22817012/163669520-e4ec9f7c-8a23-413c-9c1c-e947b433c4a2.png)
![Screenshot_20220416-171639](https://user-images.githubusercontent.com/22817012/163669521-ab5f1fda-9796-49a7-938c-ee8da8834e51.png)
![Screenshot_20220416-171648](https://user-images.githubusercontent.com/22817012/163669527-2be9cdbf-2663-422d-9aa9-4d4e1ef7859f.png)
![Screenshot_20220416-171656](https://user-images.githubusercontent.com/22817012/163669528-b914e3dc-40f6-46ad-8164-44c025423268.png)

Also I am not sure that the current UI layouts will stand forever or will be changed or not in the future. Thus themes is still a pending thing for now.

**Comment by Retro-Devils** [comment]
Thanks for the reply and awesome art !!!

**Comment by magneticchen** [comment]
Leaving this thread for wallpaper packs possibilities.

**Comment by magneticchen** [comment]
Platform wallpapers pack system added in version 1.2.3
