### ISSUE TITLE
can't "go to app" similar to other launchers when holding down android app

### ISSUE THREAD

**Issue by jesherman** [magneticchen/Daijishou#61]
this is more of a tweak, but highly desired since it's common with most launcher apps. When you hold down over a specific app to review options such as "flag app as not game" and "uninstall app" there's no option to go to the app's settings "Info" similar to Samsung UI and other apps. This would be useful to quickly open an app's permissions/settings without having to open Apps in Settings directly.

**Comment by magneticchen** [comment]
Will add it in 1.3.13
