### ISSUE TITLE
Few questions about project

### ISSUE THREAD

**Issue by DartPower** [magneticchen/Daijishou#62]
1. Do you planning to open source this project? "^__^
I think community more like GPL"ed software. this is ethical and trust-clean.
3. Planning or not use the libretro ecosystem?
You can check this:
https://www.libretro.com/index.php/mission/
https://docs.libretro.com/development/cores/developing-cores/
https://www.libretro.com/index.php/powered-by-libretro/
https://docs.libretro.com/development/cores/opengl-cores/

**Comment by savethekiddes** [comment]
1.This project is already open source, as the complete source of the frontend is here on github. As for the license, MIT is already permissive by itself.

2. This is a frontend and so it integrates with retroarch only as a frontend, providing launching roms via libretro cores and providing retroachievement syncing.

**Comment by magneticchen** [comment]
1. I currently closed-source. Have some prerequisites for open sourcing it. But probably will not GPL. It will cause licensing contamination.|
2. Not currently planned.

**Comment by gary-host-laptop** [comment]
Why does it say it uses the MIT license if it's closed source?
