### ISSUE TITLE
Add J2ME Loader for Java ME

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#63]
Since Squireljme is expected in 2023 (as the core says) and Freej2me works only with the OS java implementation (making the core completely useless if the phone isn't rooted), could you please add J2ME Loader for running Java ME and J2ME games? Thanks

**Comment by magneticchen** [comment]
Have tried J2ME Loader and no luck. :(

**Comment by savethekiddes** [comment]
You didn't manage ti make j2me loader work or you didn't managed to implement it?

**Comment by magneticchen** [comment]
I didn't make it launch from Dai previously. But I've tried again today with different parameters. It launches the game to dialog. But not open it directly.

**Comment by magneticchen** [comment]
You can redownload the java me platform to try.
