### ISSUE TITLE
Why isn't my CPU configuration supported to my Skyline emulator on my Xiaomi Redmi Note 11 Pro 4G smartphone?

### ISSUE THREAD

**Issue by Mountain558** [magneticchen/Daijishou#64]
Can someone help me with this problem, if you have counter this problem before and solved the problem. Therefore, help me right now okay.

**Comment by magneticchen** [comment]
Sorry. This doesn't related to the front-end.
Go to Skyline [Discord](https://discord.com/invite/skyline-545842171459272705) for help.

**Comment by Mountain558** [comment]
WHY DID CLOSED ME FOR????!!!!!!

**Comment by magneticchen** [comment]
The particular issue isn't associated with the topics surrounding this repository. May you pardon.
