### ISSUE TITLE
Entrateinement Updates

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#65]
While yes, this is a game launcher, it would be cool to add a new system or a even whole category of systems called Entrateinment, where to launch music, iptv or films, a little bit like kodi. I fully understand if you don't want to include this, but I still think that this would be a great idea.

**Comment by magneticchen** [comment]
You can create your custom platform to achieve that. Definitely a good idea.

**Comment by savethekiddes** [comment]
Well, already a kodi content launcher would be a nice start
