### ISSUE TITLE
Mupen64FZ doesn't open games directly

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#68]
I don't know about previous builds, but the current version of Mupen64FZ doesn't open games directly, but instead redirects you to the main menu. Thanks

**Comment by magneticchen** [comment]
I've tried mine M64Plus FZ (org.mupen64plusae.v3.fzurita) (3.0.322). And it is working.

**Comment by savethekiddes** [comment]
What? I'm running the same version.

Here's some more details:
One Ui 4
Samsung Galaxy A21S
Tried Mario Party 1, 2 and 3 and super mario n64. 
Changing in app settings doesn't do anything.
A popup about getting the game artwork appears for a fraction of a second and then nothing.

Where did you got the app from?
Is it beta?

**Comment by savethekiddes** [comment]
Well, it's seems then that is some saf nonsense. I'm not entirly sure though, so, should I close the issue?

**Comment by magneticchen** [comment]
Thanks for pointing out I've updated the platform config. Redownload the N64 platform should works for SAF.
