### ISSUE TITLE
RetroAchievements Doesn't Log-In

### ISSUE THREAD

**Issue by ThatFunnyGuyver** [magneticchen/Daijishou#69]
### Steps to reproduce
Not sure.
Tried to re-login again to RetroAchievements through the settings option and/or turning RetroAchievement's option off and on again.

### Expected behavior
RetroAchievements features work as expected (showing achievement progress in the games detail window and further RetroAchievements detail in the RetroAchievements Widget).

### Actual behavior
Seems like I'm not logged in, even after rechecking my login credentials.

### Daijishou Version
1.3.20 (296) (APK Through GitHub)

### Android Version
12 SKQ1.211019.001

**Comment by savethekiddes** [comment]
Now that I notice it happens to me too. Still on Android 12, One UI 4. Even with saved (right) credentials and retroachievements online the widget when refreshing still tells you to "Please log in".

**Comment by magneticchen** [comment]
RetroAchievements.org has updated their website to 2.0.0 causing the issues. Still in investigation at the moment.

**Comment by magneticchen** [comment]
The [newest](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.21) release should fix the issues.

**Comment by ThatFunnyGuyver** [comment]
> The [newest](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.21) release should fix the issues.

After testing [Release Version 1.3.21 (297) (APK Through GitHub)](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.21), I can confirm RetroAchievements is back and running, smooth like butter.
Closing the issue.
Thank you for a great response, and amazing execution. Daijishou 4Ever.

**Comment by magneticchen** [comment]
> > The [newest](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.21) release should fix the issues.
> 
> After testing [Release Version 1.3.21 (297) (APK Through GitHub)](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.21), I can confirm RetroAchievements is back and running, smooth like butter. Closing the issue. Thank you for a great response, and amazing execution. Daijishou 4Ever.


⠀⠀⠀⠀⠀⠀⠀⠀⠀⠁⠀⠀⠈⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⣤⣤⣤⣶⣶⣶⣶⣶⣶⣶⣶⣶⣶⣦⣤⣤⣀⡀⠀⠀⠀⠈⠀⠀⠀⠀⠀⠀⢀⣠⣤⣤⣄⡀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣶⣾⠿⠛⠋⠉⠉⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠉⠛⠻⠷⣶⣤⣀⠀⠀⠀⠀⢠⣿⠟⠉⠉⠙⣿⡆⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠲⣄⠀⠀⢀⣤⣾⠿⣛⣭⠶⠶⣤⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⠟⠉⠛⢦⡀⠀⠀⠀⠀⠀⠀⠉⠛⢿⣦⣄⣠⣾⠟⠀⠀⠀⠀⣸⡇⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⡿⠛⣡⠶⠋⠀⠀⢀⡼⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⡼⠃⠀⠀⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⣻⠟⢃⣴⢷⣤⣤⡾⠟⠁⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣿⠯⢀⡼⠃⠀⠀⣠⠞⠋⠀⠀⠀⠀⠀⠀⠀⠀⢀⡴⠋⣠⡾⢦⣄⡤⠞⠁⢀⡀⠀⠀⠀⠀⠀⠀⢀⡾⠃⢀⣾⡏⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⡿⠃⠀⡞⠀⠀⢀⡾⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠟⠀⣴⠏⠀⠀⠀⠀⠀⠀⠀⠹⣆⠀⠀⠀⠀⠀⡼⠁⢠⡟⠘⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⢸⡿⠀⠀⠀⠙⠶⠾⠋⠀⠀⠀⠀⠀⠘⣦⡀⠀⠀⢰⠏⠀⣼⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡄⠀⠀⠀⢰⡇⠀⣸⠀⠀⢿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⠀⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣄⠀⢸⠀⢰⠏⠀⠀⠀⠀⠀⠀⠀⠀⢠⡀⠀⡇⠀⣰⠀⣸⡇⠀⣿⡄⠀⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⢸⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣻⡄⣿⠀⢸⣄⠀⠀⠀⠀⠀⠀⠀⠀⠈⢷⠀⠀⣰⠇⠀⣿⡇⠀⠛⠿⠀⠸⣿⡀⠀⠀⠀⠀⣀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⢠⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⢻⡿⠀⠘⠻⠀⠀⠀⠀⠀⠀⠀⠀⠀⠸⡆⠀⡟⠀⠀⠈⠁⠀⠀⠀⠀⠀⠻⣿⣤⣤⣶⣿⡟⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠘⣿⠉⠉⠉⠙⠓⠲⢤⣄⠀⠀⠀⠀⠀⠀⠀⡿⠁⠀⠈⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠀⠀⢠⡇⠀⣧⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⡟⠉⣾⡿⠀⠀⠀⠀
⠀⠀⠀⠀⠀⠀⠀⣿⠀⠀⠀⠀⠀⠀⠀⠈⠻⣦⡀⠀⠀⠀⠀⢿⡀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣠⡴⣞⡁⠀⢠⠟⠀⠀⡉⠁⠰⣦⡀⠀⠀⠀⠀⠀⠀⢠⡇⣸⡿⠁⠀⠀⠀⠀
⠀⢀⣀⣤⣄⠀⠀⣿⡇⠀⢀⡼⠛⠻⢦⣄⠀⠈⠻⡄⠀⠀⠀⠀⠻⣆⠀⠀⠀⢸⡿⠛⠉⠁⠀⠀⠀⠉⢳⡀⠀⠀⢸⣧⠞⠛⠉⠙⠓⢶⣦⠀⢀⣴⡿⢠⣿⠁⠀⠀⠀⠀⠀
⡿⢿⠿⣿⣿⣿⡄⢹⣧⠀⠘⣧⠀⢸⠋⠈⢳⡄⠀⠹⣆⠀⠀⠀⠀⠉⠛⠲⠤⢸⠒⠛⠉⢹⣿⣿⣿⠉⢛⡇⠀⠀⢸⡧⠖⠚⣿⣶⣶⡶⠾⣦⣿⡟⠀⠸⣿⡀⠀⠀⠀⠀⠀
⣴⢿⣷⢻⣿⣿⡷⠀⣿⡆⠀⠘⡆⢸⡄⠀⠀⢹⡆⠀⠘⣷⡀⠀⠀⠀⠐⠋⠀⠈⠳⣄⣀⠀⠉⠉⣀⣴⡟⠁⠀⠀⠀⠙⢦⡀⠈⠉⠉⣠⡾⠛⢻⣧⠀⠀⣿⡇⠀⠀⠀⠀⠀
⣤⡾⣿⣿⣿⣿⢷⡀⠻⣿⡄⠀⠀⠠⣿⡄⠀⢠⡗⠀⢀⣿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠉⣉⣥⠞⠁⠀⠀⠀⠀⠀⢸⣯⣍⣉⡉⠁⠀⠀⠀⠹⣷⣼⡿⠁⠀⠀⠀⠀⠀
⣿⠀⢸⣿⣿⠗⠸⣷⠀⠙⠿⣶⣤⣀⡉⠉⠉⢻⡄⠀⢸⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠚⠋⠉⠀⠀⠀⠀⠀⠀⠀⠀⢸⡇⠀⠉⠀⠀⠀⠀⠀⢀⣿⠟⠁⠀⠀⠀⠀⠀⠀
⠋⠀⢸⣿⣿⢀⣾⣿⠀⠀⠀⠀⠙⠻⣿⣷⡄⠀⠙⠆⠘⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⠀⠀⠀⠀⠀⠀⣞⠀⠀⠀⠀⠀⠀⠀⢀⣾⡟⠀⠀⠀⠀⠀⠀⠀⠀
⠀⢠⣾⣿⣯⣄⣿⣇⠀⠀⠀⠀⠀⠀⠘⢻⣧⡀⠀⠀⢀⣬⢿⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⡾⠁⠀⠀⠀⠀⠀⠀⣿⢷⠀⠀⠀⠀⢀⣴⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⣾⣿⣿⣿⣿⣿⣿⣄⠀⢀⣤⡀⠀⠀⠀⠻⠿⣶⣾⡏⠀⠀⢹⡟⠓⠶⠶⠶⣤⡀⠀⠀⠀⣴⣿⡀⣶⢶⣄⠀⠀⠀⠀⢸⣼⡃⠀⢀⣴⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⠀⣿⣿⣿⣿⣿⣿⣿⣿⣦⣹⡿⠏⠀⠀⠀⠀⠀⣰⡿⠁⠀⠀⢸⡇⠀⠀⠀⠀⢸⡇⠀⠀⣸⠃⠀⠀⠈⠀⠙⢧⣤⣤⣤⠾⠃⣇⠀⢸⡿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢸⡟⣿⣿⣿⣿⣿⣿⣿⡿⢿⣿⣿⣿⡀⠀⢀⣲⣿⠃⠀⠀⠀⣼⡇⠀⠀⠀⠀⢸⡇⠀⢰⠇⠀⠀⠀⠀⢀⣀⣀⣀⣠⣀⠀⠀⢻⡀⣼⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢸⣿⣿⣿⡿⠿⠿⣟⣻⣿⣿⣿⣿⣿⣇⠀⣠⡿⠃⠀⠀⠀⠀⣿⠁⠀⠀⠀⠀⠀⠀⠀⢸⡀⠀⠀⢀⣴⠟⠁⣀⠙⢁⣈⢷⡄⠉⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⢸⣿⣿⣻⣿⣇⣈⣿⣿⣿⣿⣿⣿⣿⠿⣶⣿⠃⠀⠀⠀⠀⢠⣿⠀⠀⠀⠀⠀⠀⠀⠀⠈⠀⠀⠐⢿⡗⠒⠚⠛⠒⠛⠓⢺⠇⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡿⠁⠀⣠⡿⠃⠀⠀⠀⠀⠀⢸⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠻⣤⣀⠀⠀⢀⣠⠏⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠉⠁⠀⠀⠀⠀⠀⠀⣾⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣉⣉⣉⣉⠁⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡟⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠹⢿⣦⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⢿⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠙⠳⢦⡀⠀⠀⠀⠀⠙⣿⡆⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡅⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠻⢶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⡇⠀⠀⠀⠀⠀⣿⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠛⠶⣤⣄⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⡇⢀⣠⣤⣴⣾⣿⣿⣿⣦⣤⡀⠀⠀⠀⠀⠀⠀
⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠙⠻⠶⢶⣤⣀⣀⣀⣠⣤⡶⠟⠛⣿⣿⣿⣿⣿⣿⣿⣿⣿⠙⢿⣷⣦⡀⠀⠀⠀
⢠⡿⣿⣿⣿⣿⣿⣿⣿⣿⣷⡄⠀⠀⣀⠤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⠇⠀⠉⠉⠀⠀⠀⠀⢸⣿⣿⣿⣿⣿⣿⣿⣿⣿⡆⠀⣯⠙⣿⣦⡀⠀
⠋⣴⠏⠙⣿⣿⣿⣿⣿⣿⢿⣿⣦⡀⠳⠤⠈⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⠚⠉⠀⠀⠀⠀⠀⠀⢀⣴⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⣿⠦⣾⣤⣼⣿⣷⡄
