### ISSUE TITLE
AetherSX2 fails to launch game (all front-ends do)

### ISSUE THREAD

**Issue by MonkoftheFunk** [magneticchen/Daijishou#7]
So this is an issue with all front-end launchers on android now. It uses the SAF content URI to launch games. 
'content://com.android.externalstorage.documents/tree/primary%3AGames%2FPS2/document/primary%3AGames%2FPS2%2FEFMI.chd"
These have the best discussions by launchbox dev..

https://forums.launchbox-app.com/topic/64553-bootpath-for-aethersx2-and-other-maybe/

https://forums.launchbox-app.com/topic/62596-launchbox-for-android-new-version-beta-testing/?do=findComment&comment=400662

But it might not be possible, 
https://forums.launchbox-app.com/topic/64553-bootpath-for-aethersx2-and-other-maybe/?do=findComment&comment=401227

AetherSX2 dev doesn't like front-ends and might stop it's support.

It's just something to note. I'll put more details as I find them.

**Comment by MonkoftheFunk** [comment]
Arcbrowser got around it by using a saf contenuri proxy app to launch emulators and games from
https://arcbrowser.com/safproxy
But planned to integrate the code in the future

**Comment by MonkoftheFunk** [comment]
(you can decompile to see how it works, I can help with that if you need) https://maximoff.su/apktool/?lang=en

**Comment by MonkoftheFunk** [comment]
You can close... My AetherSX2 didn't have the rom path loaded... It works...

**Comment by magneticchen** [comment]
Thanks for the information. Currently AetherSX2 works fine with Daijishou on my retroid pocket 2+ somehow. 🤔

**Comment by MonkoftheFunk** [comment]
Ya it all works, my bad, I closed it
