### ISSUE TITLE
Add Retroarch Cores as a platform

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#70]
There are certian Retroarch standalone cores that can be launched individually without any rom. It would be cool to add a system called "Retroarch Cores" and put all of the relevant cores there (for example the minecraft clone Craft)

**Comment by magneticchen** [comment]
Cores like Fbneo, MAME have added. The request of "Game & Watch" is also added. Since the issues doesn't specify core specifically. Will close the issue.
