### ISSUE TITLE
Support for Chromecast with Google TV

### ISSUE THREAD

**Issue by stzokev** [magneticchen/Daijishou#72]
Add support for Chromecast with Google TV. I was able to side load it on mine, but it crashes when I try to add path to the games. Otherwise navigating with Xbox controller or the Chromecast remote seems to be working just fine.

Thanks for your hard work!

**Comment by magneticchen** [comment]
I've bought Chromecast with Google TV to try Dai on TV. But android TV is missing SAF. Which is required by Dai. So the plan is hanged.

**Comment by AnAvidEditor** [comment]
Another vote for this whenever it becomes possible. Great app!

**Comment by stzokev** [comment]
>But android TV is missing SAF. Which is required by Dai. So the plan is hanged.
Launchbox and Dig are both working although each with its flaws, so they clearly have workaround for the missing SAF. I really like yours best however, so crossing finger you figure things out!

**Comment by stzokev** [comment]
Just installed the Android 12 update to Chromecast and it's even worse. Now I can't even add a platform as the Bottom button line with the 3 buttons (Index URI, Cancel and Import) is missing.

**Comment by magneticchen** [comment]
> Just installed the Android 12 update to Chromecast and it's even worse. Now I can't even add a platform as the Bottom button line with the 3 buttons (Index URI, Cancel and Import) is missing.

Yes I’ve tried it. And I don’t even know why this is happening.

**Comment by dadog92** [comment]
I'm not a dev. but it seems related to the same problem. I'm so eager to have Dai working on my chromecast. hope it helps
![Screenshot_20221028_154316](https://user-images.githubusercontent.com/116894987/198621364-efacd612-e100-4274-9e0b-2e0f19055fa7.jpg)

**Comment by GustavoGomez092** [comment]
Any plans on using an external file/folder picker library to not depend on SAF?

**Comment by stzokev** [comment]
@magneticchen Is there some sort of a workaround e.g. to copy already populated config files from a handheld where Daijishou works correctly to the Chromecast install dir? It really is a shame that a single step renders this excellent software unusable.

**Comment by yhusei** [comment]
Is there still no solution to choose the game route? In xiomi's adnroid tv, this closing or crashing problem also occurs when choosing a route.

**Comment by magneticchen** [comment]
Another update: nowadays many emulators have upgraded their file API implementations to SAF. Which makes Android TV less plausible for frontends, since SAF is not supported on Android TV. Therefore not only file picker is missing, `file.uri` also is not supported.

**Comment by magneticchen** [comment]
To avoid wasting time, anticipations and efforts of everyone. I unfortunately declare that Android TV will not be supported by Dai.

**Comment by AnAvidEditor** [comment]
No problem. Thanks for trying! 

- Matt

On Mar 13, 2023, at 6:35 PM, TapiocaFox ***@***.***> wrote:

﻿
To avoid wasting time, anticipations and efforts of everyone. I unfortunately declare that Android TV will not be supported by Dai.

**Comment by spanillo** [comment]
Peccato veramente che non sia compatibile con google tv , qualcuno può  consigliarmi un'app simile ?

**Comment by bitrot-alpha** [comment]
For FireTV users see my comment for how to setup Daijishou in #637. FireTV still ships `com.android.documentsui` but it is basically impossible to navigate with a remote. Daijishou still launches emulators just fine on my Fire Stick HD (sheldon) and Fire Stick 4K. If Daijishou crashes when attempting to set paths, you may have disabled the Files app. Re-enable it with `adb shell pm enable com.android.documentsui`.

**Comment by widardd** [comment]
I got it working on current AndroidTV 14, all I needed was a file manager thats able to provide a DocProvider for apps that rely on SAF.

I know two by now:

https://play.google.com/store/apps/details?id=com.docreader.fileviewer.pdffiles.opener

And the currently developed Ultimate File Manager over on AndroidTV subreddit.

Apart from that Daijisho is working flawlessly on my Xiaomi Mi Box S 3rd Gen.😊

No crashes ever, not even during setting things up.👍

**Comment by stzokev** [comment]
@widardd Thanks for this. Unfortunately the file manager from the link does not work with external storage (where all my roms are), it does not map the file paths correctly and daijisho cannot start the games, it ends up with error that the file is no longer there. I suppose you only tested with internal storage.
Just to be complete I tested this file manager with PPSSPP and it has the same problem when trying to specify rom folder, namely wrong path mapping. So in short, it is definitely a problem with the file manager and not daijisho.
Could you provide link for the 2nd file manager as there are a few with that "unique" name and I am not sure which one you refer to.
Thanks!

**Comment by widardd** [comment]
> [@widardd](https://github.com/widardd) Thanks for this. Unfortunately the file manager from the link does not work with external storage (where all my roms are), it does not map the file paths correctly and daijisho cannot start the games, it ends up with error that the file is no longer there. I suppose you only tested with internal storage. Just to be complete I tested this file manager with PPSSPP and it has the same problem when trying to specify rom folder, namely wrong path mapping. So in short, it is definitely a problem with the file manager and not daijisho. Could you provide link for the 2nd file manager as there are a few with that "unique" name and I am not sure which one you refer to. Thanks!

The file manager works here for internal aswell as external storage for every single emulator including ppsspp. 
UFM is still being finalized and not public, it will even include SMB/FTP storage. The dev told me it shouldn't take more than a few hours to get the next and final version out.

**Comment by stzokev** [comment]
@widardd Not sure how it could work for you, but not for me unless you're using a different Android TV version. I am on latest 14.
P.S. I've experienced the same issue with the UFM and reported it to the developer who confirmed the problem and said he's going to fix it.

**Comment by widardd** [comment]
> [@widardd](https://github.com/widardd) Not sure how it could work for you, but not for me unless you're using a different Android TV version. I am on latest 14. P.S. I've experienced the same issue with the UFM and reported it to the developer who confirmed the problem and said he's going to fix it.

UFM just implemented this after I talked to the guy and his first implementation didnt work. That was 2 or 3 days ago, I am waiting for the next build.

Heres a video using dai and ppsspp via the working file manager for a rom on external storage (usb) successfully to launch a psp game:

https://youtu.be/-LGegBVYyvQ?si=StTtkrviX9pzWAb3

![Image](https://github.com/user-attachments/assets/abcb6c70-1680-4bbd-a3b0-06228e7e650d)

**Comment by stzokev** [comment]
@widardd Strange, it does not work on mine, I don't have youtube, so here are a few screenshots with the File Manager from Play Store:
https://postimg.cc/0r8dxxXH
Pay attention to the path string. Somehow even with this wrong path daijisho manages to scan the folder, but when I try to start a game I get the error: 
https://postimg.cc/svHJw8mv

And here is what the path looks like in UFM with their built from 2 days ago. I might have hijacked your thread in the reddit explaning to the dev that it doesn't work:
https://postimg.cc/Xry9xvXP
Notice how the path looks better with the exception of the /tree/ part in the uri.

**Comment by widardd** [comment]
> [@widardd](https://github.com/widardd) Strange, it does not work on mine, I don't have youtube, so here are a few screenshots with the File Manager from Play Store: https://postimg.cc/0r8dxxXH Pay attention to the path string. Somehow even with this wrong path daijisho manages to scan the folder, but when I try to start a game I get the error: https://postimg.cc/svHJw8mv
> 
> And here is what the path looks like in UFM with their built from 2 days ago. I might have hijacked your thread in the reddit explaning to the dev that it doesn't work: https://postimg.cc/Xry9xvXP Notice how the path looks better with the exception of the /tree/ part in the uri.

Oh I see the problem now. You're using {file.path} rather than {file.uri}.
If I do that I get the same error.
Are you players and platforms in dai not updated properly?

**Comment by stzokev** [comment]
@widardd I've always used the paths button to scan my collection. I can find URI only for loading games through json files and for that button to work you don't need no file manager. So if you mean something else, could you explain how to get this working? I am not using daijisho on any other android devices, I play retro games only on my android tv device where I am trying to get daijisho working. Thanks!
P.S. In regards to testing PSP games, I was referring to the standalone PPSSPP emulator where there is Browse game folder button which also does not map the path properly.

**Comment by widardd** [comment]
> [@widardd](https://github.com/widardd) I've always used the paths button to scan my collection. I can find URI only for loading games through json files and for that button to work you don't need no file manager. So if you mean something else, could you explain how to get this working? I am not using daijisho on any other android devices, I play retro games only on my android tv device where I am trying to get daijisho working. Thanks! P.S. In regards to testing PSP games, I was referring to the standalone PPSSPP emulator where there is Browse game folder button which also does not map the path properly.

Edit your ppsspp player in dai to use file.uri rather than file.path.

**Comment by stzokev** [comment]
@widardd I am not sure how to do that, can you explain how you've used file.uri in daijisho? I am looking at your video and you click on the exact same button I click on. So how is the result different? In other words what I am trying to say is, your workaround appears to have some more details you're missing out to share.

**Comment by widardd** [comment]
> [@widardd](https://github.com/widardd) I am not sure how to do that, can you explain how you've used file.uri in daijisho? I am looking at your video and you click on the exact same button I click on. So how is the result different? In other words what I am trying to say is, your workaround appears to have some more details you're missing out to share.

That's not the case. I don't use workarounds. By default the players in Daijisho use file.uri here, I never changed that. Go into dai settings and edit your players to use Uri instead of path like it's described there.

**Comment by stzokev** [comment]
@widardd My players are auto configured by daijisho, I haven't touched anything. I've just clicked edit on the 3DO player as example and the default is {file.path}, not uri. If manual edit of each of these is required, then this is the missing step you haven't mentioned until now. If this is not what you mean, then I am afraid I do not follow you and would appreciate further guidance. Thanks

Update: updated the main players for 3DO and Amiga (not the ones with 32/64 bit in the name) to file.uri and now I no longer get the error and retroarch is starting, but no game actually plays and after 5-10 secs it shows the ARN popup that Retroarch has crashed and do I want to wait or close it. I've never used daijishou before, so I assumed it would be a simple setup, apparently not.

**Comment by widardd** [comment]
> [@widardd](https://github.com/widardd) My players are auto configured by daijisho, I haven't touched anything. I've just clicked edit on the 3DO player as example and the default is {file.path}, not uri. If manual edit of each of these is required, then this is the missing step you haven't mentioned until now. If this is not what you mean, then I am afraid I do not follow you and would appreciate further guidance. Thanks

I don't use the 3DO player, any other player I use has URI as default. For example redream.
You're correct in that 3DO seems to use file.path, but I couldn't tell you wether that's the issue.

I had an issue with DraStic, tried changing URI to PATH and it didn't solve my issue and I got the error you seem to be getting then.

That is why I proposed to change PATH to URI on your end, like it is described in Daijisho.

On my end I'm still using the auto config for:

DraStic
DuckStation
GBA.emu
GBC.emu
M64Plus FZ
MD.emu
NES.emu
PPSSPP
Redream Premium
Snes9x EX+

**Comment by stzokev** [comment]
Ok I've just setup PSP on Daijisho which uses file.uri by default and the games start successfully. What I've noticed however is that around half of my psp collection does not have any images i.e. nothing was scraped. Since the purpose of a front end is to make everything look polished and beautiful, the lack of images for the gallery surprised me and it kind of defeats the purpose of me using this app. Is there a setting to change scraper source?

**Comment by TheBrightNebula** [comment]
Hey ya’ll, I was wondering if anyone here has got RetroArch booting from Daijisho? I was able to use that “My File” File Manager app workaround to select my ROM directories for Daijisho but it fails to boot any vote from Retroarch giving me the same error that @stzokev has in the image linked here: 

https://postimg.cc/svHJw8mv

If anyone has it working please let me know how you have done so! Thanks glad we finally have a workaround to get some stuff going on newer Android TVs!

**Comment by stzokev** [comment]
Read previous comments how to resolve this error. But in the end it didn't help much, because games would seemingly launch, but Retroarch would crash after 10-15 seconds.

**Comment by widardd** [comment]
Is there a specific reason you guys insist on RetroArch?
You could try adding the rim paths to RA aswell. I've had the situation with at least one emulator that it required to have the ROM folder added as well just like in Daijisho.
