### ISSUE TITLE
Add Game & Watch system

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#73]
A Game & Watch was the first type of handheld console produced by Nintendo and it's a genre of "consoles" in their early stages. They can be simulated via the [GW libretro core](https://docs.libretro.com/library/gw/).

**Comment by magneticchen** [comment]
I am aware of that but the boxarts is not stadardized so I am still thinking.

**Comment by magneticchen** [comment]
Have added without scraping boxarts.

**Comment by savethekiddes** [comment]
Perfect
