### ISSUE TITLE
melonds can‘t work

### ISSUE THREAD

**Issue by crhhahaha** [magneticchen/Daijishou#74]
https://user-images.githubusercontent.com/87603208/190910737-a387c657-69f9-499f-b1ce-6d362fba88d8.mp4

**Comment by savethekiddes** [comment]
Does MelonDS have direct storage permission? (Does melonDS under his info page > Permissions  have Storage permission?). If yes is it granted?

**Comment by savethekiddes** [comment]
I don't really use melonDS and therefore I don't know how it works. Anyway there could be some viable options:

1) Have you checked that melonDS has Storage permission? You can do it by going to the Recents tab, long pressing on Daijishou icon, go to About this app (or similar), go under permissions and search for a storage related permissions. If there is, enable it. If it's already enabled pass to method 2.

2) Welp, you are going to get you hands dirty. Click the edit button at the bottom right of the system, search Emulator Settings in that page, and under the two input boxes there should be some bubbles with some package names. Find the one of melonds and click it (do NOT click the x at the right of the bubble, just the bubble). It should prompt you to the emulator edit page. Inside the input boxes there, search for the `file.path` string. Once you have located that, long press it and switch it with `file.uri`. Save changes and the game should launch correctly.

If none of this works, it's probably an issue with melonDS itself. If you want suggestion on another emulator, i use drastic and it worked out of the box without even opening Drastic first.

**Comment by crhhahaha** [comment]
Sorry，I field...
It is indeed the problem of melonds, he does not have storage permissions, both of your methods have not been successful, is there a chance to solve this problem?

https://user-images.githubusercontent.com/87603208/190913052-682c3237-c959-4042-8f7b-667d1e8d98fc.mp4

**Comment by savethekiddes** [comment]
What it's by default
![What it's by default](https://user-images.githubusercontent.com/88157500/190913322-f9cdb920-a8f0-43d2-9961-73ad3e4efd05.jpg)
What it should be
![What it should be](https://user-images.githubusercontent.com/88157500/190913400-0227dd7f-0bd8-457c-bac2-6ff0352dc959.jpg)

**Comment by savethekiddes** [comment]
Have you tried doing this?

**Comment by crhhahaha** [comment]
> 默认情况下 应该是什么 ![默认情况下是什么](https://user-images.githubusercontent.com/88157500/190913322-f9cdb920-a8f0-43d2-9961-73ad3e4efd05.jpg) ![它应该是什么](https://user-images.githubusercontent.com/88157500/190913400-0227dd7f-0bd8-457c-bac2-6ff0352dc959.jpg)

First image
I tried the "uri" of the second image and restarted all the apps but it still doesn't work

**Comment by crhhahaha** [comment]
> 情况下 应该是什么 ![情况下是什么](https://user-images.githubusercontent.com/88157500/190913322-f9cdb920-a8f0-43d2-9961-73ad3e4efd05.jpg) ![它应该是什么](https://user-images.githubusercontent.com/88157500/190913400-0227dd7f-0bd8-457c-bac2-6ff0352dc959.jpg)

first image
I tried the "uri" of the second image and restarted all the apps but it still doesn't work

**Comment by crhhahaha** [comment]
> Have you tried doing this?

![nfdnsfjrdkzf](https://user-images.githubusercontent.com/87603208/190913763-99269197-61a5-4137-91c1-5e91ca95236d.jpg)
like this right? i tried

**Comment by savethekiddes** [comment]
Then I don't know what to say

**Comment by savethekiddes** [comment]
Does melonds works with other forntends, like dig?

**Comment by crhhahaha** [comment]
> Does melonds works with other forntends, like dig?

Neither dig nor launchbox work

**Comment by crhhahaha** [comment]
![image](https://user-images.githubusercontent.com/87603208/190916567-875d4318-513f-4526-9289-af3d6a79922d.png)

**Comment by crhhahaha** [comment]
Maybe the path of the uri is inconsistent with the melonds？

**Comment by rafaelvcaetano** [comment]
Hey guys! I'm the developer the melonDS port for Android. Sorry for all this trouble, but this is a melonDS issue. It will be fixed in the next release. Meanwhile, you can  try using nightly builds from GitHub which you can find here: https://github.com/rafaelvcaetano/melonDS-android/actions/workflows/main.yaml

**Comment by crhhahaha** [comment]
> Hey guys! I'm the developer the melonDS port for Android. Sorry for all this trouble, but this is a melonDS issue. It will be fixed in the next release. Meanwhile, you can try using nightly builds from GitHub which you can find here: https://github.com/rafaelvcaetano/melonDS-android/actions/workflows/main.yaml

thanks, melonds android is excellent, i like it so much！

**Comment by magneticchen** [comment]
> Hey guys! I'm the developer the melonDS port for Android. Sorry for all this trouble, but this is a melonDS issue. It will be fixed in the next release. Meanwhile, you can  try using nightly builds from GitHub which you can find here: https://github.com/rafaelvcaetano/melonDS-android/actions/workflows/main.yaml

Wow. Thanks for your works. Can't wait to play and tinker with it. 😀
