### ISSUE TITLE
Remember last preferences in Apps Page 

### ISSUE THREAD

**Issue by German-Herrador** [magneticchen/Daijishou#75]
When i select options like only games or alphabetical order the launcher will not remember this preferences and if i enter again it will be set as default (this is the only problem, the launcher does remember platform, widgets and highlights preferences and also if i flag an app as a game or not)

**Comment by magneticchen** [comment]
Thanks for reporting. Previous update does break the function! And I didn't notice at all. Will fix that in next version!

**Comment by magneticchen** [comment]
Have fixed it in [1.3.23](https://github.com/magneticchen/Daijishou/releases/tag/v1.3.23).
