### ISSUE TITLE
Add Fairchild ChannelF system

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#77]
![6tw10z](https://user-images.githubusercontent.com/88157500/190966267-defa5a0e-f7fa-4cb5-97da-48abff903cf0.jpg)
The FCF was the first game console to support cartridges. It can be emulated via the FreeChaF libretro core. Thanks.

**Comment by magneticchen** [comment]
Add Fairchild ChannelF platform.
