### ISSUE TITLE
Centered aspect ratio when displaying game list

### ISSUE THREAD

**Issue by yhusei** [magneticchen/Daijishou#78]
just as you can choose to expand or not the initial menu of consoles, it would be good to do the same with the list of games, which seems to me to leave a lot of empty space on the cover. I attach some images as it would look like with an option to center it.

current stretched:   https://ibb.co/HGvB1K3

modified centered:  https://ibb.co/YBVSSNZ

**Comment by savethekiddes** [comment]
That's a lot of screen estate lost, especialky when you want to use your phone as a handeld.
