### ISSUE TITLE
Cannot launch Yaba Sanshiro 2 pro

### ISSUE THREAD

**Issue by suetlung** [magneticchen/Daijishou#79]
Daijisho ver : 1.3.24
Yaba sanshiro ver: 1.9.4

1. add Saturn platform.
2. Install Yaba Sanshiro 2 pro from play store
3. copy Saturn rom to a folder
4. config Daijisho to scan the folder and finded the rom.
5. confirm Saturn platform is set to use saturn - yabasanshiro 2 pro
6. select the rom to launch.
7. It black out and returned back to launcher without loading the game.

Update:
Tried with no problem on Android 9. 
This issue only happens on Android  > 10

**Comment by magneticchen** [comment]
Someone on discord point out that it requires you to put files in certain folder to make it works.

**Comment by magneticchen** [comment]
![Screenshot_20220921-221305](https://user-images.githubusercontent.com/22817012/191527914-4d8a6347-03c2-4b18-804d-d3898b65f837.png)
