### ISSUE TITLE
Hide certain apps or two folders (tabs)

### ISSUE THREAD

**Issue by MonkoftheFunk** [magneticchen/Daijishou#8]
Ability to hide apps that aren't needed. Though I understand it's the also a home launcher, so have maybe 2 tabs one for maybe put the games and then the rest?

**Comment by MonkoftheFunk** [comment]
Or just that it tracks app launches and sorts them by that so the most used are at the top

**Comment by magneticchen** [comment]
Hello again my friend. Thanks for your suggestions. You can hide apps  in version 65(1.1.39) now.
