### ISSUE TITLE
Palm OS Support

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#82]
![senpai-of-the-pool](https://user-images.githubusercontent.com/88157500/191984240-9d39d1ea-022b-48aa-94c4-82fe5c8d2839.png)
Palm OS was a 32 bit operating system designed for Lenovo and Motorola smartphones. As always, it can be emulated with retroarch (wih the Mu core). Thanks.

**Comment by magneticchen** [comment]
Plam OS platform added.
