### ISSUE TITLE
Add Android as a REAL system

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#83]
So first I want to say that this is not a duplicate of issue [#37](https://github.com/magneticchen/Daijishou/issues/37). The way that android games are integrated as of now is pretty much nonsense and is one of the few things that daijishou handles worse than many other emulators:

- Why display games in the app section and not in the main games page? (Yes I'm aware of the "Games Only" option, but it's still a gimmick)
- Why "hide" games between emulators that also shows up as games? (For a person that as 4 to 5 android games and 10 emulators?)
- The only workaround to make games a little more distinguishable is add them as widgets, which is even more of a gimmick when you want them in alphabetical order.

I'm concious that this isn't as easy as making up a platform json file, but it would really game changing if Android would show up as a system like NES or GameBoy (like any other frontend does).

P.S.: Adding Android as a platform doesn't necessearly means to get rid of the "Games Only" option, as some people enjoy it, but at least giving the option on how to display them is a really greay thing.

**Comment by magneticchen** [comment]
There is already an Android platform configuration file that can be imported.

https://github.com/magneticchen/Daijishou/blob/main/platforms/Android.json.deprecated

By simply remove the .deprecated.

But I don't like it. I considered Android apps more like a native components for myself. So I made the option secondary.

**Comment by magneticchen** [comment]
![IMG_20220924_234906_024.png](https://user-images.githubusercontent.com/22817012/192107067-aa86e0c6-2ad6-4d56-867d-cd7b855111dc.png)
![IMG_20220924_234901_029.png](https://user-images.githubusercontent.com/22817012/192107075-619c8c42-9b73-4a7a-886f-01eb5ee58758.png)


Will even scrape the descriptions.

**Comment by savethekiddes** [comment]
I didn't notice.
[I forked your repo](https://github.com/savethekiddes/Daijishou/blob/main/README.md)  and added instruction on how to install. Thank you.

**Comment by magneticchen** [comment]
The thumbnail icons are grabbed from the device.

**Comment by savethekiddes** [comment]
I don't mean the box art, but the art of the system itself. Like for example snes has mario kart as its art.

**Comment by magneticchen** [comment]
Depends on which wallpapers pack you choose.

**Comment by magneticchen** [comment]
Oh. Wait I didn’t added it.

**Comment by savethekiddes** [comment]
Ok thank you. I'll close the issue.

**Comment by savethekiddes** [comment]
Just for curiosity, how can you add a custom wallpaper pack (if you can)?

**Comment by magneticchen** [comment]
No worries, I am adding it anyway.

**Comment by magneticchen** [comment]
> Just for curiosity, how can you add a custom wallpaper pack (if you can)?

There is an index.json file where you can map the image file name.

**Comment by savethekiddes** [comment]
Oh I didn't knew it was mapped there, I'll check

**Comment by savethekiddes** [comment]
So yeah you were right but unlike platforms you can't change the uri of the index.json in the app and thus you can't create custom themes.

**Comment by magneticchen** [comment]
Yes, you can only add it online for now.
