### ISSUE TITLE
Retroachievements dont show logo images when it's complete

### ISSUE THREAD

**Issue by Elbearno** [magneticchen/Daijishou#87]
Hi,
I play on my Odin Pro, when i go to see achievements on a game, i can see images on achievements logo i dont have earned but it's don't display on achievements i have already earned.
![IMG_20220928_191922](https://user-images.githubusercontent.com/114608260/192848343-20cc8b86-a53e-4bd4-b318-3a1ac9cb8688.jpg)
I tried to refresh or change display style, but nothing change.

**Comment by magneticchen** [comment]
Can you try to clean the cache?

**Comment by Elbearno** [comment]
Yes i'm hardcore player , i tried to clean the cache of google chrome but nothing happen...
My daijisho version is 1.3.25(301)

**Comment by magneticchen** [comment]
Do you know how to use Google Chrome Deb tools?

**Comment by magneticchen** [comment]
Fixed in 1.3.26 version.
