### ISSUE TITLE
Add Flash Support

### ISSUE THREAD

**Issue by savethekiddes** [magneticchen/Daijishou#91]
So, you probably thinked about this already, but maybe you didn't find a working implementation. Well, now swf files can be played via [Ruffle](https://ruffle.rs/demo), and open source reimplementation of the flash player. 

Please, try to figure out if you can launch a file with android arguments and if possible (but absolutely not necessary) to directly launch in fullscreen.

There is a goldmine of point and clicks games that could be played via a smartphone. Thanks.

(I'm aware that saving is impossible)

**Comment by savethekiddes** [comment]
Already working on it by myself

**Comment by magneticchen** [comment]
:100:
