### ISSUE TITLE
Add support for folders 

### ISSUE THREAD

**Issue by jadflat** [magneticchen/Daijishou#95]
Commodore 64 has over 30k releases and having them all in section doesn't work very well.
Is it possible to add support for sub folders?

**Comment by magneticchen** [comment]
Subfolders are supposed to be supported already. Is it the extension formats causing the issue?

**Comment by savethekiddes** [comment]
You can add more than one path already

**Comment by jadflat** [comment]
> Subfolders are supposed to be supported already. Is it the extension formats causing the issue?

Sorry, I wasn't clear. I want to see and use the sub folders while in the Commodore section.  Not just have it scan the sub folders and display everything at once

**Comment by magneticchen** [comment]
Not plan to arrange items in the folder-like pattern. It create unwanted complexities in the current state. 30k is a rare use case. And main reason is that there are still a lot of casual features have not added yet. But 30k is definitively a interesting problem to challenge with.

**Comment by cargath** [comment]
I don't have 30k games, but i would still like to be able to see subfolders in the library view. Sometimes i just need that additional element of organisation - e.g. so my SNES rom hacks don't mix with the regular games. I like to prepare a bunch of Link to the Past / Super Metroid randomizer seeds and i don't want to scroll a single long list where all of them are mixed together.
