### ISSUE TITLE
Hardoce RA automaticaly disable on aethersx2 when open with Daijishou

### ISSUE THREAD

**Issue by Elbearno** [magneticchen/Daijishou#99]
Hi,
I enable the hardcore mode of retroachievements on AetherSX2.
When i try to open a PS2 game with the Daijishou launcher , it's open AetherSX2 but the hardcore mode of retroachievements is disable.
When i restart the game directly on AetherSX2, it's enable the hardcore mode.
I use the last version of Daijishou and AetherSX2.

Can you fix this ?

Thanks !

**Comment by magneticchen** [comment]
Sorry, but this seems to be an issue related to AetherSX2.
